<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YaTidak</name>
   <tag></tag>
   <elementGuidId>04494315-2e0c-4c89-a422-602360575c89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#satdik_confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='satdik_confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3bdbee4b-4f85-4d2a-b53c-61dfecc27281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>satdik_confirm</value>
      <webElementGuid>732080cf-8a7f-4d2c-8a40-c2e05cf267f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>satdik_confirm</value>
      <webElementGuid>0788e42f-49db-433a-8101-f3222ebae410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fieldinput form-select</value>
      <webElementGuid>c578bc7d-e489-4bfa-9c88-458f038acfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fd9c4a04-d60b-4129-8374-5888d71fe6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Ya
Tidak
</value>
      <webElementGuid>71eb44cd-eb34-4cdf-96c6-8d23d87f5b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;satdik_confirm&quot;)</value>
      <webElementGuid>67fd7576-105e-4f6f-b62f-f626e395cdbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='satdik_confirm']</value>
      <webElementGuid>126f0f3f-9e4f-4d96-8444-f3b782303ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div[3]/select</value>
      <webElementGuid>262ee94d-1844-49a1-8eff-bce87e444f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Satdik'])[6]/following::select[1]</value>
      <webElementGuid>e462f873-94ea-4a6f-af26-e73916ff5afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[2]/following::select[1]</value>
      <webElementGuid>7b3f0921-988c-4c85-8928-4d38c97a9da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[3]/preceding::select[1]</value>
      <webElementGuid>888d33d8-393b-40d2-8939-f205547ccdb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/select</value>
      <webElementGuid>6ae9ef3d-8868-4247-a186-a34a12d1d156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'satdik_confirm' and @id = 'satdik_confirm' and (text() = '
Ya
Tidak
' or . = '
Ya
Tidak
')]</value>
      <webElementGuid>673f993b-6448-486c-a7f9-0403b5878eea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
