<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Role</name>
   <tag></tag>
   <elementGuidId>ad016360-671f-4f17-b9c4-c0fb54a0324c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-opt_role_administrator-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-opt_role_administrator-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a58a3a6a-c4b6-47d8-9cae-dc3e4af1fbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>1fbda8d6-2465-4f37-bcdd-67874f7b737b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-opt_role_administrator-container</value>
      <webElementGuid>6b2994af-fb32-44ae-b68e-88ce74e8db24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>104de36c-4e98-4317-aa66-736cce6fdfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b00933cf-cfbb-4bf2-bb9e-9aaff1da4d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>6c493a1a-4ff2-4de6-a4d0-98ec58db9dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-opt_role_administrator-container&quot;)</value>
      <webElementGuid>4852677e-8cb4-47ff-8c04-dc822adb3250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-opt_role_administrator-container']</value>
      <webElementGuid>905d7ace-bf08-4329-ae30-259fda489540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_search']/div/div/div[2]/span/span/span/span</value>
      <webElementGuid>0fce3d6d-b658-4ee2-ba66-6b6942324e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Soal'])[1]/following::span[4]</value>
      <webElementGuid>6dc846d3-a4c3-491c-bc6c-a9584e2db9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template Sertifikat/Ijazah'])[1]/following::span[5]</value>
      <webElementGuid>e5f9c0b3-4332-4112-820c-a3820bf626f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satdik'])[2]/preceding::span[4]</value>
      <webElementGuid>6992e214-e682-4747-9ceb-dfacd9356e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>2de7ca9e-9080-49f1-87bb-e75824b1f5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-opt_role_administrator-container' and (text() = 'Role' or . = 'Role')]</value>
      <webElementGuid>8ff8c87d-01b9-4908-9d92-a527c0c44a80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
