<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Satdik</name>
   <tag></tag>
   <elementGuidId>6f45ea79-0643-4a21-828f-776678ea4157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-opt_unit_name-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-opt_unit_name-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>35e303c7-e0e3-4a00-8cf0-cf19fbbb5a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>949f324c-90f7-41d6-b776-ed93cc480498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-opt_unit_name-container</value>
      <webElementGuid>246099c3-31cc-4cd4-99f9-7016ae264422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b96a6349-ec1f-45ba-aae6-38174d341893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>400d72ce-f1b7-4e8a-8899-a43a361399e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Satdik</value>
      <webElementGuid>27fb38ff-3651-4f68-9320-881cd76efa90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-opt_unit_name-container&quot;)</value>
      <webElementGuid>c4c6fb07-10f8-4af6-9413-a15dc85b2388</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-opt_unit_name-container']</value>
      <webElementGuid>7eb2670d-6c40-4884-b893-b5d93690e6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_search']/div/div/div[3]/span/span/span/span</value>
      <webElementGuid>6784076b-b645-4bf9-bdb6-2a605cf4bbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::span[6]</value>
      <webElementGuid>5fe16c57-bafe-4624-b087-21201545daf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::span[4]</value>
      <webElementGuid>b8ab6c16-afab-4f96-9d25-dad12c82ac6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span/span</value>
      <webElementGuid>3c2c610a-f8e0-438e-99e5-3f5faba3c0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-opt_unit_name-container' and (text() = 'Satdik' or . = 'Satdik')]</value>
      <webElementGuid>2b0f2c18-ed7a-4568-93d7-be03cc9e0891</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
