<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah</name>
   <tag></tag>
   <elementGuidId>b30a909a-59f8-46a7-9c12-3bd42e0d30bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-danger.save-question.waves-effect.waves-light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-survey-question']/div[2]/div/div[6]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89b19cc4-e81e-4ef3-b826-65b14c8b2df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger save-question waves-effect waves-light</value>
      <webElementGuid>efbf28e6-385b-4315-9239-b9cb8132f08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah</value>
      <webElementGuid>05c56830-bb72-4e4c-bd6b-d50b2fd08f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-survey-question&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;mb-4 float-end mt-3&quot;]/button[@class=&quot;btn btn-danger save-question waves-effect waves-light&quot;]</value>
      <webElementGuid>bc5863cf-7649-429d-962a-5bdbe4df8aad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-survey-question']/div[2]/div/div[6]/button</value>
      <webElementGuid>f83a549e-9861-424e-b9da-c4aacefe9ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[2]/following::button[1]</value>
      <webElementGuid>e4a1db45-9d55-4af9-ad6c-658ebafb418b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[6]/following::button[1]</value>
      <webElementGuid>b0ce3429-781d-4b34-94db-de9c5e5be2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pertanyaan'])[4]/preceding::button[1]</value>
      <webElementGuid>a67a2971-8f02-446a-83b2-b2b4ad9c03de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah']/parent::*</value>
      <webElementGuid>f558ed6f-2931-4225-81db-07a339eb79f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>5843ad90-539f-42c5-927d-e33f5b2132ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Tambah' or . = 'Tambah')]</value>
      <webElementGuid>23766bff-6485-4066-94b0-36f49fbf83e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
