<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_survey_start_date</name>
   <tag></tag>
   <elementGuidId>39af366b-0a9c-407e-9e82-5cd71bcd62fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#survey_start_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='survey_start_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4c2a286-63ff-4810-8d06-c35fd188158c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e188ccf-38d4-4b6c-a7b4-484d3c347122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker</value>
      <webElementGuid>f20893f1-1d3e-4ad4-95c2-2cac4f554416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>survey_start_date</value>
      <webElementGuid>ae974308-929d-4023-87ff-96900ed84f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>survey_start_date</value>
      <webElementGuid>06e504d0-0ddb-4729-a84b-397edfe9656b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>a9075335-e2a8-41af-879d-dd023b74767c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>06556879-3153-4552-aa4a-7ad1b4e7f1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;survey_start_date&quot;)</value>
      <webElementGuid>d379dcd0-9295-4a48-a657-12293dca3817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='survey_start_date']</value>
      <webElementGuid>a9187ce3-544c-4653-9bd1-41150ed291ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div/input</value>
      <webElementGuid>6e781aa4-18a8-49fd-b5bf-825477df16d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>6e4981b3-d5af-48cf-8862-83f7e57d8c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'survey_start_date' and @id = 'survey_start_date' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>2aee1f98-d40f-4a17-ad40-66fb9af37869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
