<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_mandatory_question</name>
   <tag></tag>
   <elementGuidId>eed2735d-340c-47fa-9fb7-3507438e637f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mandatory_question</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mandatory_question']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ad04f29-883d-4c07-8744-1ee81efb1b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>67e80016-e56e-42a1-92b4-0aaf6e61b4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>ce5aefcd-346d-41df-91bc-e7306a7df30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mandatory_question</value>
      <webElementGuid>714619c8-37a1-48e0-9387-daac670a99d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mandatory_question</value>
      <webElementGuid>74fd8f90-1c44-4779-b799-c2d0ce50fa31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatory_question&quot;)</value>
      <webElementGuid>39292525-151f-4e8d-aac1-0737d37bf05b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mandatory_question']</value>
      <webElementGuid>3d779214-3526-4b8b-8220-2e08439af2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-survey-question']/div[2]/div/div[2]/input</value>
      <webElementGuid>cbc09597-bc0d-46e7-8f56-1aebc5104b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a62b7771-7ab4-474f-90da-b861036b20ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'mandatory_question' and @id = 'mandatory_question']</value>
      <webElementGuid>683170a9-cea0-4517-8ad6-8aa460e87725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
