<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_survey_name</name>
   <tag></tag>
   <elementGuidId>b2532fe3-da76-44c0-b14c-c1f2535aa34b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#survey_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='survey_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9a5c7c7-a230-408f-99c7-f3ac55464c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8856a0a-adc2-404c-8258-9f0198bcaed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>700ed4bb-3efb-428e-8f45-8fa50343bb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>survey_name</value>
      <webElementGuid>4c2a50ea-6e46-44d7-ab2f-fbc688b247e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>survey_name</value>
      <webElementGuid>4929bf3c-fe5a-48bd-a11d-a1e67bbb469b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi Judul Survei</value>
      <webElementGuid>86b59ebf-2dd6-4948-8e8a-e464a70cdf5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b6541e4a-4a50-4172-9bcb-9b29d9084c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;survey_name&quot;)</value>
      <webElementGuid>57c7f4a2-4105-4110-9c2b-44860f5592ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='survey_name']</value>
      <webElementGuid>a38797d4-6935-41cf-abb7-3294b0f9386f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div/fieldset/div/input</value>
      <webElementGuid>93a0809d-fff3-442a-af6c-688dd901304d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>8470391a-77a4-458a-9eca-059b128df241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'survey_name' and @id = 'survey_name' and @placeholder = 'Isi Judul Survei']</value>
      <webElementGuid>49bf593e-1ccb-4a47-b6b5-b8ac4ea13210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
