<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_survey_finish_date</name>
   <tag></tag>
   <elementGuidId>998bc760-526a-42b0-af3b-b26ce8380732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#survey_finish_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='survey_finish_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cf9ec1f-3ac6-443d-8cc4-a3286f86c128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec3c72a6-f6d6-48fa-9391-f976b9a0aa62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker</value>
      <webElementGuid>b5b68d66-cd63-4751-8dfb-a4956b6a3c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>survey_finish_date</value>
      <webElementGuid>94fec6a0-1f22-4849-bb93-aef521cbf8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>survey_finish_date</value>
      <webElementGuid>602e4b15-95c4-44a7-9055-38df89868e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>9f11b16c-fb9f-474e-a874-78cc143dcbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f2980e59-753a-4345-83dc-b1350ffd673e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;survey_finish_date&quot;)</value>
      <webElementGuid>dfe8147c-3151-4c9e-9396-4e8917e5dc62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='survey_finish_date']</value>
      <webElementGuid>d139e6e3-3060-4384-9b5d-12bcc82e81c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div[2]/input</value>
      <webElementGuid>1b6e9c26-f91d-4862-a19d-d3285bdb7388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>fc30c81b-544d-4f2d-a1da-11421599f29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'survey_finish_date' and @id = 'survey_finish_date' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>33add4e7-772e-4c5d-bcdd-cc5245ad0e9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
