<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_score_items</name>
   <tag></tag>
   <elementGuidId>ad450c84-5b07-4a85-aa39-90970418dd25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#score_items</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='score_items']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2173f37f-0d1f-40eb-8b2d-d408bc753b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a5ffeb54-abd3-4281-83a6-d76cefaa6439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>score_items</value>
      <webElementGuid>e7775920-f71d-49c2-a8ad-7c6da808a4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score_items</value>
      <webElementGuid>f960a072-3b0e-464d-b7b7-d3ecc07973aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>96472191-7806-49a5-8917-76eac02ff5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7de3104f-a7e3-4abe-bbef-18a41db89a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;score_items&quot;)</value>
      <webElementGuid>f36e5840-ec54-4abf-9d4a-ef98c96f58f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='score_items']</value>
      <webElementGuid>93156927-0ba1-4303-87c1-21aa81c5c9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-number-answer-choices']/input</value>
      <webElementGuid>06505d0a-2661-4806-a11a-335cea0abe1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>40706ed3-6026-4ede-8be0-55ddbbf92ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'score_items' and @id = 'score_items']</value>
      <webElementGuid>70ea7865-6976-4060-93d5-53d5dd7b75e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
