<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_is_all_participants</name>
   <tag></tag>
   <elementGuidId>142d6cf9-db3e-406f-a846-75778d3b1437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#is_all_participants1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='is_all_participants1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f9023d3-dd81-49a8-a85f-148936bcecf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1a2405aa-f0e1-40f7-9b27-f7f737de246e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>092328e7-bf1f-4860-bcec-9e6eec3e8819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_all_participants</value>
      <webElementGuid>902c90b5-6e75-401d-8361-6760ed67639e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_all_participants1</value>
      <webElementGuid>6ba4b6de-5343-4180-897a-9f442de9d1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>71515c39-7063-4306-ac9d-d523fcec8c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is_all_participants1&quot;)</value>
      <webElementGuid>79c5a425-5fad-4655-985d-2f6ed2715f2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='is_all_participants1']</value>
      <webElementGuid>cbe6e4ce-bf45-40d5-af31-e1c56e1a521e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/fieldset/div/div/div/div/input</value>
      <webElementGuid>e358a2a3-3031-4d41-b74c-44fe600780cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>4acd104a-3333-46ad-b862-6c451e9e06d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'is_all_participants' and @id = 'is_all_participants1']</value>
      <webElementGuid>bc6d0640-4a78-4d36-9216-a9925ad97353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
