<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>05_user only</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>20e82f08-b953-418c-a656-7693b974e17f</testSuiteGuid>
   <testCaseLink>
      <guid>dd34f77d-062f-469a-8efe-150abc0b5e4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05_user/01_kepala bandiklat</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9385112d-bdbe-414a-a4ef-718a5f195d18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4d73ad7-2dde-4f27-b1cb-63f630bff7da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05_user/02_data widyaiswara</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83f087f7-4581-45c2-a311-074a958dbf7f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0c51e55-18d0-4cf0-a170-d9256ccad6dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05_user/03_data peserta</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ab28119-a80f-42de-9057-3815d6478307</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed40a012-4adf-436f-96dd-f04b99653074</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05_user/04_administrator</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cfbbe27-8393-41af-9500-b8d828929a9c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7faf991-6613-47eb-a012-ca06fe2ebfa3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05_user/05_matgaklin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffbb7843-0a17-458d-a04e-2053aadee23a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fdcf0297-e84f-450e-84b7-4de2155969e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05_user/06_penyelenggara</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0946633a-e1ed-4eaa-acad-6c578ee2d475</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
