<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_PPPJ GELOMBANG II TAHUN 2016 - Kelas 2</name>
   <tag></tag>
   <elementGuidId>0b740661-0915-40d8-967c-5691f53a7b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-training_class-results']/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.select2-results__option.select2-results__option--highlighted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ee3607f0-5762-4ae3-bc9e-ac0e221e3683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>1e6d22b0-a9f7-43e7-8163-198f75140dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f5d48e56-134d-4a2b-b258-f2dc3c5bfe0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c78d0d44-2e3d-442c-a75f-cf0f98fc7553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>3428211a-95ad-4eb1-9c9a-bee89be92204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PPPJ GELOMBANG II TAHUN 2016 - Kelas 2</value>
      <webElementGuid>3367842f-afba-45b8-9b54-0d88f69cb215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-training_class-results&quot;)/li[@class=&quot;select2-results__option select2-results__option--highlighted&quot;]</value>
      <webElementGuid>ef93c8bf-8adb-4d93-ba47-6988defdf4b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-training_class-results']/li[3]</value>
      <webElementGuid>6dc7c798-1319-4861-aba2-d87c8a8d5fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PPPJ GELOMBANG II TAHUN 2016 - Kelas 1'])[2]/following::li[1]</value>
      <webElementGuid>e7db8f9b-a89a-4aa5-bc2d-177d1691adce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Searching…'])[1]/following::li[2]</value>
      <webElementGuid>b9e51118-73e8-4e44-8e44-ec529ec90177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[3]</value>
      <webElementGuid>dd98bf06-dd19-49ee-8cff-9f57947b46e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'PPPJ GELOMBANG II TAHUN 2016 - Kelas 2' or . = 'PPPJ GELOMBANG II TAHUN 2016 - Kelas 2')]</value>
      <webElementGuid>b7ee734b-91e2-44df-a8d3-79cb06d043b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
