<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Satdik</name>
   <tag></tag>
   <elementGuidId>3db31ff4-c31e-487f-af06-673cd0e2a152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-organizing_agency-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-organizing_agency-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>621388cc-35b9-49fd-a674-bbc1eb8b0134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>594690de-fe7c-4b96-aad6-db3c27da60b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-organizing_agency-container</value>
      <webElementGuid>d46a0e3a-f411-4e11-9ec0-1160c10da7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>87b6992f-c02d-400f-aa1d-1b387288451c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ccb2d772-115a-4ee8-93bc-10e3078e5dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Satdik</value>
      <webElementGuid>c9b26afd-c1c3-410b-ac6e-44e3d1b0ec90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-organizing_agency-container&quot;)</value>
      <webElementGuid>20b8a613-9e96-4127-9bd8-9e18c324107e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-organizing_agency-container']</value>
      <webElementGuid>19bc4733-0f52-4761-b5ef-4407dddb31dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='text-editor']/div/div/div/table/tbody/tr[2]/td[2]/span/span/span/span</value>
      <webElementGuid>21449430-eddb-491c-9962-e4a7c00b8695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satdik'])[2]/following::span[4]</value>
      <webElementGuid>1473caae-f3f3-4a17-956d-b153e4098493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diklat'])[2]/following::span[5]</value>
      <webElementGuid>7becde85-a950-4335-b7a0-6be571c25d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelas'])[3]/preceding::span[4]</value>
      <webElementGuid>efb24a76-3430-43ab-94b0-66c06be8c881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>3c9655fd-1fb8-4c0a-9a5e-56774a2450c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-organizing_agency-container' and (text() = 'Pilih Satdik' or . = 'Pilih Satdik')]</value>
      <webElementGuid>2615ee95-89e7-44f5-81b5-7f0b3fcef37c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
