<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Latsar Golongan II Gelombang 2 Tahun 2022</name>
   <tag></tag>
   <elementGuidId>ed094cbf-f08c-479c-b743-4776288fa2f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-cco_id-results']/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.select2-results__option.select2-results__option--highlighted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>cc586c5e-8192-4fd5-85fe-45f3301416e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>b74d66d0-4c06-41f5-a700-d81338dc15a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cb2ebaea-d5d5-4b8c-aca9-b4fa5bf569b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>88451231-eaac-4d28-bd94-432ceb62cb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>942bdc44-c442-4248-b639-a052e040e2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Latsar Golongan II Gelombang 2 Tahun 2022</value>
      <webElementGuid>45fbc8fa-e4e9-4da7-954e-75e561f6c656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-cco_id-results&quot;)/li[@class=&quot;select2-results__option select2-results__option--highlighted&quot;]</value>
      <webElementGuid>ea888047-30df-410b-be9c-bc40a970e1c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-cco_id-results']/li[2]</value>
      <webElementGuid>a4b26cbc-70ce-4550-9cc4-e02a7868a9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teknis'])[1]/following::li[1]</value>
      <webElementGuid>00f88f7a-d794-46d3-9871-48847f45287b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[1]/following::li[2]</value>
      <webElementGuid>41aec23d-291c-464d-86bf-e974986a8a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEKNIS ADMINISTRASI KEJAKSAAN GOL. II GEL. 6 2022'])[1]/preceding::li[1]</value>
      <webElementGuid>5f9d9c6b-f1b1-45c0-a44b-5917d251cd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diklat Teknologi Informasi Terpadu'])[1]/preceding::li[2]</value>
      <webElementGuid>4b7c6147-b3b0-42ef-987c-2f275978562b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Latsar Golongan II Gelombang 2 Tahun 2022']/parent::*</value>
      <webElementGuid>855a5f2f-400b-41bb-b479-ff5d0edc324e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[2]</value>
      <webElementGuid>bf0b2e9b-bb13-4b69-8605-e5c3f88ea94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Latsar Golongan II Gelombang 2 Tahun 2022' or . = 'Latsar Golongan II Gelombang 2 Tahun 2022')]</value>
      <webElementGuid>eaac5172-35ba-4e36-9c31-a34ef22f3248</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
