<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>import file 2</name>
   <tag></tag>
   <elementGuidId>41a49f2a-4fca-4b41-8afe-9913146fa8e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#file</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e871655-fc16-4205-87ba-6523437703e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1d80a852-ae65-44d9-91a4-2797b7cac428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>713e9a3c-6212-43ef-b2b5-7a93fe907b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>8096bee8-e2d3-437d-a886-6abfce427d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>6d47c589-3bec-4505-b2ac-d8e690bd6868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>791fd128-0e0d-4220-ba2d-315bbe5950a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>handleFile(this)</value>
      <webElementGuid>9648cec3-7b56-4e2a-b432-4be997676d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel</value>
      <webElementGuid>ea83a3f0-780a-419e-b7fc-87d0d9480b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;file&quot;)</value>
      <webElementGuid>8d97a9cc-f210-4a93-aea3-10ab6b98970c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='file']</value>
      <webElementGuid>6b4b25aa-d658-4c83-b547-e85e92e40e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/input</value>
      <webElementGuid>510c76dc-d629-41dc-86b7-41b6e3e53129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>2ba8a4bc-f895-4eeb-8999-8d069b97e484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'file' and @name = 'file']</value>
      <webElementGuid>57be3109-fdb8-4919-af2c-c4737b8a634d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
