<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__score_item_minimum</name>
   <tag></tag>
   <elementGuidId>855c39ba-4202-404b-a003-579bd8163ef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#score_item_minimum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='score_item_minimum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>174e4030-3840-4be6-b613-d6b701e380b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>cb86d89d-3f3c-4246-b315-2908d53c1ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>score_item_minimum</value>
      <webElementGuid>a74a38d3-8d1b-4227-9bfd-886bf0303ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score_item_minimum</value>
      <webElementGuid>b88a48a9-907d-4ea2-a167-e4d08219e755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>12754158-9e7b-46b3-9576-7704872e33a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nilai Batas Kelulusan</value>
      <webElementGuid>f9c856c3-e9f8-4503-8342-b8869474770e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;score_item_minimum&quot;)</value>
      <webElementGuid>558d7572-3e27-4e4c-a601-e3b4d64cc40c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='score_item_minimum']</value>
      <webElementGuid>fa645cdd-ab6c-4415-a0cf-c2986891fe4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[2]/div[2]/div/input</value>
      <webElementGuid>67df682b-76cb-4d2f-bf2f-20300368f354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>f7f1f270-d4ee-47ef-8d21-d67826ba570e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'score_item_minimum' and @id = 'score_item_minimum' and @placeholder = 'Nilai Batas Kelulusan']</value>
      <webElementGuid>6c45b595-c957-4e0f-82ac-e6a2132d181d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
