<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nilai Minimum Kelulusan_course_minimu_71e3ec</name>
   <tag></tag>
   <elementGuidId>dd345208-cd37-4d8c-ba14-6854e80c6dc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#course_minimum_graduation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='course_minimum_graduation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1c1215a-ed13-43ab-ac1b-ac889065cd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fdd2cd54-8719-4593-b790-d86cd9984fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>course_minimum_graduation</value>
      <webElementGuid>f440f8ba-91a3-4211-bbde-a399167d4c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>course_minimum_graduation</value>
      <webElementGuid>dfdb140d-d7e0-4460-a783-0f49380d18f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pr-50</value>
      <webElementGuid>c094fa67-63ab-46e6-84cd-81bd8df8e2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nilai Minimum Kelulusan</value>
      <webElementGuid>39c658e0-1914-4a4c-8fac-a286e608a578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>a3ae042c-bffd-4471-97f5-928482700d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;course_minimum_graduation&quot;)</value>
      <webElementGuid>87d320f6-701a-4603-b1ed-84c6c8b20512</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='course_minimum_graduation']</value>
      <webElementGuid>3f5318a0-4447-4b25-9045-8973572d9798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div[7]/div/div/input</value>
      <webElementGuid>71abc6b5-f705-4816-9648-4e189a46fcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>5dabd274-3e5e-4da8-8013-4652d3058f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'course_minimum_graduation' and @id = 'course_minimum_graduation' and @placeholder = 'Nilai Minimum Kelulusan']</value>
      <webElementGuid>2cdddde6-34aa-45e4-9e58-100850b3cac7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
