<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Jam - Praktek_course_duration__03e586</name>
   <tag></tag>
   <elementGuidId>226e1f4d-6617-4566-9af2-a0d9aa10084f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#course_duration_practice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='course_duration_practice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cbdd6ee-2b2c-4682-a349-2140ee44c4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4681447-d74e-487b-be87-ad66845b1c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pr-50</value>
      <webElementGuid>4ed480a1-2825-4e19-9fe2-d0068643aafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>course_duration_practice</value>
      <webElementGuid>6644b920-346f-49dc-967d-b722b1841ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>course_duration_practice</value>
      <webElementGuid>beb59fc1-442d-4666-b139-f88a94765bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>098b84dc-aadd-49d1-adc4-2f222c5629c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c3248745-164b-46d3-9d16-f5176e3e4c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;course_duration_practice&quot;)</value>
      <webElementGuid>c3323057-f4ff-42f4-b53b-274ffcdf5e80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='course_duration_practice']</value>
      <webElementGuid>63769878-d499-425a-a919-0a53933a2aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div[5]/div/div[2]/div/input</value>
      <webElementGuid>3cf08940-38be-412d-bc31-2c624419e4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/input</value>
      <webElementGuid>25cf6dd0-dd6a-473e-9b8f-09c60c5c8640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'course_duration_practice' and @id = 'course_duration_practice' and @placeholder = '0']</value>
      <webElementGuid>4b3a19f0-a502-4f5e-93e9-8982eeafa43a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
