<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nilai Maksimal Kelulusan_score_type_maximum</name>
   <tag></tag>
   <elementGuidId>bb807cb7-fe8b-482c-b373-f7b1abe58dfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#score_type_maximum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='score_type_maximum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b720463-767e-4f98-ad12-0af35bf14248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ab1fd990-7f59-427f-9d17-f0b7cd55551b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>score_type_maximum</value>
      <webElementGuid>72384667-e59f-4625-a650-4babe1457a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score_type_maximum</value>
      <webElementGuid>2032da1e-6abe-4220-a64f-083eeddf3171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d8d18cc5-a91a-402b-851b-6720352b39e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nilai Maksimal Kelulusan</value>
      <webElementGuid>b6828ad8-7a95-42f7-a842-c2c1088ef8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9987783c-aefe-4319-b071-bd9662739ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;score_type_maximum&quot;)</value>
      <webElementGuid>da400e87-8b9b-4162-b310-1738de9f2e95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='score_type_maximum']</value>
      <webElementGuid>86d86f20-30e7-4d4c-a151-1647f5b90627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_score_type']/div[2]/div[3]/div/div/input</value>
      <webElementGuid>065cc433-f688-40b9-8168-a653f932762c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>73ff1f9f-d613-4820-ad8a-61733b7a8923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'score_type_maximum' and @id = 'score_type_maximum' and @placeholder = 'Nilai Maksimal Kelulusan']</value>
      <webElementGuid>7d99d8a9-942c-4dd5-926a-f5bc41dc7317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
