<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_course_code</name>
   <tag></tag>
   <elementGuidId>3f66c40b-0bf2-4989-8605-9bc841873b7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#course_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='course_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dce0677e-03a8-4461-aded-5977c3c02090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d276e7e7-c22e-4918-bbc8-ace31dca4357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>course_code</value>
      <webElementGuid>eba89e3e-5304-4d93-b9bc-12969b3fa810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>course_code</value>
      <webElementGuid>08c22726-7f71-4462-9da8-524452ac8bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>03ed5f1a-8715-4806-a6a6-5f556edb6f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi Kode Diklat</value>
      <webElementGuid>13c8bbb1-827d-42be-8a3a-2c4be5ff51df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>8c2a91e4-9291-4e94-913b-69a066e01577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f1&quot;)/div[@class=&quot;card-body p-0&quot;]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;course_code&quot;]</value>
      <webElementGuid>48293c9c-e314-4bbb-bb56-ced0048c8fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='course_code']</value>
      <webElementGuid>c24fe5f5-fcfc-405b-9a14-43d7c4b3ffae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div/input</value>
      <webElementGuid>e6366e44-5076-4ea6-8fc7-c9d124599e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>6d4d9746-f484-4e0b-a3f4-55d903f1e43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'course_code' and @id = 'course_code' and @placeholder = 'Isi Kode Diklat']</value>
      <webElementGuid>6a732c46-5c11-41f5-bcec-c2985e114557</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
