<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Frekuensi_schedule_frequency</name>
   <tag></tag>
   <elementGuidId>75180602-3489-4d7b-8446-ea93126a57db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fullday</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fullday']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a39f266-4cbc-4487-8e98-bd1578e58457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>4d9e9b2b-faf4-4a35-9137-6d8b12f59966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a3363665-478d-4a69-8b5f-57986df3308c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>schedule_frequency</value>
      <webElementGuid>10d7845d-0fee-4821-adfe-5591cb744702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>07caea6a-93dc-481a-95ea-61ebb8c61c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullday</value>
      <webElementGuid>1bac6713-82fa-4cec-86dd-8516992240fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullday&quot;)</value>
      <webElementGuid>b99c70f3-5282-4dad-80d4-f6f105cf06e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fullday']</value>
      <webElementGuid>eb986cec-4c9f-450f-a47b-c5a52dc10a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div[3]/div/div/input</value>
      <webElementGuid>649b038f-601e-4407-a56c-8a8f0e3df58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>b30f1c48-948e-4f92-8b4e-a65383a0d6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'schedule_frequency' and @id = 'fullday']</value>
      <webElementGuid>c7a98179-0ee5-4eef-9806-b6bd70026390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
