<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__score_item_weight</name>
   <tag></tag>
   <elementGuidId>91567629-6b94-4922-a55b-dcbcc57c3542</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#score_item_weight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='score_item_weight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>705698e1-a921-4b34-a679-0adfcdb5868e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d50e0741-e09b-47c7-810f-b618357e3a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>score_item_weight</value>
      <webElementGuid>e2723205-1e41-43a5-9bcf-43f2b9fdbbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score_item_weight</value>
      <webElementGuid>f333eb6a-dc66-499e-8c40-9d02041d6560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f468aad4-955c-4089-b988-3228349facae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bobot</value>
      <webElementGuid>031fda84-99e7-41ae-aa62-06aa97637854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;score_item_weight&quot;)</value>
      <webElementGuid>2ef6e84b-d597-4e7c-a284-4b0f7778c722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='score_item_weight']</value>
      <webElementGuid>8b0535f5-742a-443d-b640-eb2cdcb34444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[2]/div/div/input</value>
      <webElementGuid>16344119-b8fb-4a11-bce2-c88888ea2971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>a799b8e9-03c8-4230-b83d-6e04434d5427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'score_item_weight' and @id = 'score_item_weight' and @placeholder = 'Bobot']</value>
      <webElementGuid>f07d658e-c4f2-4a1a-af19-50789d16045e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
