<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_--- Kelompok Menu ---</name>
   <tag></tag>
   <elementGuidId>54fdaba8-549d-45f8-9506-d2cbf017e9a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-score_type_group-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-score_type_group-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8443c7a0-7d2d-4088-9cc0-c7ed70085a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>bdfe89ff-98ba-4a60-a590-2cd9ee304ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-score_type_group-container</value>
      <webElementGuid>814b2705-d3be-4783-a592-eb189b4d33cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>5d80e6ef-74d7-4a71-bcd3-818753c5bae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3982e884-da91-4f0b-9567-a0992d0324c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--- Kelompok Menu ---</value>
      <webElementGuid>2a5ee6cc-b6b3-4bae-9ecb-c8b2edef9e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-score_type_group-container&quot;)</value>
      <webElementGuid>0afbcfc4-c414-4271-a94e-d5a614b82122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-score_type_group-container']</value>
      <webElementGuid>fd814b90-2599-45ff-ade2-731a33053579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_score_type']/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>b92a7ddd-183e-4168-8498-1a53ce5d72dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[8]/following::span[4]</value>
      <webElementGuid>4e89101a-440e-4fd5-99cf-6df6ff5f895a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>38d6ef25-1530-4c70-8e2b-76304eeaae96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-score_type_group-container' and (text() = '--- Kelompok Menu ---' or . = '--- Kelompok Menu ---')]</value>
      <webElementGuid>5787be88-fec9-41df-8b3b-048900033ef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
