<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Tahun</name>
   <tag></tag>
   <elementGuidId>b4a4a611-962d-4587-afcf-28a8b57678e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-opts_years-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-opts_years-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3b77b08f-f301-426e-a5bc-dc296bcea452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>146fd629-aaac-47e5-b20c-30c2148c0c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-opts_years-container</value>
      <webElementGuid>336b5488-dccd-4c64-8d15-482478f84bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>46497be4-fcce-4dc0-bc5f-f2164eacb76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c02a975-2731-4505-98db-4e36c8ab8615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Tahun</value>
      <webElementGuid>c637b58d-bb60-45a5-8004-685bea20cfbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-opts_years-container&quot;)</value>
      <webElementGuid>a7b003c2-f039-4b75-99ab-fec163b463f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-opts_years-container']</value>
      <webElementGuid>11030481-7eb9-4b3b-9620-cda36673e876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_search']/div/div/div[3]/span/span/span/span</value>
      <webElementGuid>868f2d27-4905-47c1-ae86-9a1e1c032690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::span[6]</value>
      <webElementGuid>edfc6c9d-b4c6-45a3-98a3-5205f455d945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Kelas'])[1]/preceding::span[4]</value>
      <webElementGuid>6e01ca11-dc9b-4814-b595-fb81ea904d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span/span</value>
      <webElementGuid>2a22b31b-d2b8-44f5-933f-b057d5f880fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-opts_years-container' and (text() = 'Pilih Tahun' or . = 'Pilih Tahun')]</value>
      <webElementGuid>a7dd9e1e-16f1-42a2-8c00-bd104aa961fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
