<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Belum Lengkap_btn btn-light btn-sm no-but_994e61_1</name>
   <tag></tag>
   <elementGuidId>7ec32057-9894-4dc2-b25f-f604272bc412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[10]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87743387-fdf9-4e89-9b98-a416b4746310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light btn-sm no-button no-shadow </value>
      <webElementGuid>a38400d3-ac8e-4b43-b3a3-da1a380c58c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://101.255.121.243:1180/classroom/attendance/57</value>
      <webElementGuid>cc353e5b-6679-4b75-98ba-76c8fa21e5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>a03d5b80-3eb5-4ca1-9d04-001e72386d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>bce0e727-5e09-4415-acb8-240ec3e2d6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Nilai &amp; Kehadiran</value>
      <webElementGuid>5464c8bd-1672-42c3-90fd-58c1d9c95d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Nilai &amp; Kehadiran</value>
      <webElementGuid>768d153f-96bf-4e50-8f9c-7c7ffb4ff03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip855380</value>
      <webElementGuid>92fe06bc-e1df-4850-8e56-0685faa00127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[10]/a[@class=&quot;btn btn-light btn-sm no-button no-shadow&quot;]</value>
      <webElementGuid>de661c6a-d46a-47d9-abd9-b5c32a2d2b56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[10]/a[2]</value>
      <webElementGuid>d2eff754-466c-41d2-93e5-bbda7c7408dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Lengkap'])[2]/following::a[2]</value>
      <webElementGuid>c5fe93bf-da8c-4781-88d4-c48b99cbd95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusdiklat Mapim'])[2]/following::a[2]</value>
      <webElementGuid>438ca8d5-c3cd-4eda-b3fc-854ec9c729b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries (filtered from 10 total entries)'])[1]/preceding::a[2]</value>
      <webElementGuid>6cf989d7-30dc-4181-95fc-d2b1c3f8d3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://101.255.121.243:1180/classroom/attendance/57']</value>
      <webElementGuid>fe86b061-750a-4356-95ca-97d64f9154e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/a[2]</value>
      <webElementGuid>1fe052ad-6e48-46e2-a391-9b53b76dae4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://101.255.121.243:1180/classroom/attendance/57']</value>
      <webElementGuid>64a2e0aa-51d3-42c0-b95c-85c5e41751e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
