<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_praktik_btn btn-light btn-sm waves-effect_421e01_1_2</name>
   <tag></tag>
   <elementGuidId>254e00ee-11b4-4aca-850b-8a2b21ca8252</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='view_mapel']/div/div/div/table/tbody/tr[4]/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ad45b24-09c7-4b6c-8467-eb68c0479570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light btn-sm waves-effect waves-light</value>
      <webElementGuid>a5c2a44d-33b1-489b-bc24-2a8860645fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://101.255.121.243:1180/classroom/scores/lesson/57/29</value>
      <webElementGuid>867a0ab1-a96d-465c-bf24-541c5bfe5da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>57468e00-8209-4bd2-8689-799f63de799d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>e8a1554a-801f-40b1-b11b-3eb4af29ead9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>84ef7204-b62a-4e79-a867-d8714c9ea3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>a4e1fcde-6769-4aa3-af4f-b30f1d858afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip133399</value>
      <webElementGuid>2806a1fd-d34d-46c6-801c-5eb2471365fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view_mapel&quot;)/div[@class=&quot;card px-2 py-3 mt-4 fs-poppins&quot;]/div[@class=&quot;row mx-n1 mt-3&quot;]/div[@class=&quot;col-md-12&quot;]/table[@class=&quot;table table-striped table-hover row-border order-column dataTable&quot;]/tbody[1]/tr[4]/td[4]/a[@class=&quot;btn btn-light btn-sm waves-effect waves-light&quot;]</value>
      <webElementGuid>8b9e3838-a921-4f24-a253-a84db211b3a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_mapel']/div/div/div/table/tbody/tr[4]/td[4]/a</value>
      <webElementGuid>fedd114f-afd4-4b1f-859f-611bd2f38f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='praktik'])[4]/following::a[1]</value>
      <webElementGuid>ddf74e90-e35f-4f88-9471-b53b699e84c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='teori'])[4]/following::a[1]</value>
      <webElementGuid>eafe3a4a-f8bf-4587-96f1-da406e2ce0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MP-001 - Agama dan Budi Pekerti'])[1]/preceding::a[1]</value>
      <webElementGuid>5de75944-d830-47fd-901e-a2490b96ef7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='teori'])[5]/preceding::a[1]</value>
      <webElementGuid>67cb38b8-ab36-415a-acca-e832c49c38e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://101.255.121.243:1180/classroom/scores/lesson/57/29']</value>
      <webElementGuid>a2794f4a-9d5d-4061-98f9-c63080edf313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/a</value>
      <webElementGuid>a4d08615-8fa5-4965-a469-f37284c3dc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://101.255.121.243:1180/classroom/scores/lesson/57/29']</value>
      <webElementGuid>c83e2e2d-3696-40bf-9d4a-bf017985e0ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
