<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_praktik_btn btn-light btn-sm waves-effect_421e01_1_2_3</name>
   <tag></tag>
   <elementGuidId>e12c1c83-10da-4eda-b33b-d29e2e7ab1d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='view_mapel']/div/div/div/table/tbody/tr[5]/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71243f63-2adc-40d1-b14c-a6ec81fcabbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light btn-sm waves-effect waves-light</value>
      <webElementGuid>d78d9bdd-d66e-4178-bf4b-4015cb3e6d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://101.255.121.243:1180/classroom/scores/lesson/57/1</value>
      <webElementGuid>e50419c9-4665-400c-9fd9-d42744f98811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>69295783-b499-466c-9566-9017639b7c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>3902eed5-c281-4c58-818c-5e0db3b9d886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>3f75293c-adf4-488f-b897-30ae18ecb639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>d8a01b5c-0775-4b05-a6e7-41d6219c8fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip609699</value>
      <webElementGuid>0e2ad30c-938d-44d7-a6bc-308ae741f591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view_mapel&quot;)/div[@class=&quot;card px-2 py-3 mt-4 fs-poppins&quot;]/div[@class=&quot;row mx-n1 mt-3&quot;]/div[@class=&quot;col-md-12&quot;]/table[@class=&quot;table table-striped table-hover row-border order-column dataTable&quot;]/tbody[1]/tr[5]/td[4]/a[@class=&quot;btn btn-light btn-sm waves-effect waves-light&quot;]</value>
      <webElementGuid>eac31463-091e-4998-8904-5f5b8e314e23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_mapel']/div/div/div/table/tbody/tr[5]/td[4]/a</value>
      <webElementGuid>4d26bf84-10ba-4e19-9e3d-cb31c5a2f1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='praktik'])[5]/following::a[1]</value>
      <webElementGuid>2d3dea89-2524-4419-9fab-f3919ec9c326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='teori'])[5]/following::a[1]</value>
      <webElementGuid>49483749-3cd1-4a7c-9f4f-60c2ad73d9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MP-015 - Upaya Hukum Pidana'])[1]/preceding::a[1]</value>
      <webElementGuid>70f1fc7d-244b-4a91-83b8-3eb55375a514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[5]/preceding::a[1]</value>
      <webElementGuid>e66c6bea-d7ac-4836-8c0e-c4c50a893719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://101.255.121.243:1180/classroom/scores/lesson/57/1']</value>
      <webElementGuid>3fe94de6-7ce8-49c5-a374-12d815fd9733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/a</value>
      <webElementGuid>b80f3968-30d5-4db4-ae3b-b282d0c09519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://101.255.121.243:1180/classroom/scores/lesson/57/1']</value>
      <webElementGuid>a10f8ba6-7e62-4502-bc78-9967a7f87ec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
