<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_praktik_btn btn-light btn-sm waves-effect_421e01_1</name>
   <tag></tag>
   <elementGuidId>5390816c-7f18-4741-8c4c-e4a7d684342a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='view_mapel']/div/div/div/table/tbody/tr[3]/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7dc11314-be43-4240-9fca-dd8f506b46b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light btn-sm waves-effect waves-light</value>
      <webElementGuid>694635b5-5667-44e4-8488-2ae30cec6f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://101.255.121.243:1180/classroom/scores/lesson/57/12</value>
      <webElementGuid>0bb18b7e-7f9b-42d2-a50e-1c9573a13691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>e35d5609-2026-478f-ac4b-566cc917999d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>f3798db9-71c0-4e8f-ba44-927cbf5a9354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>4a5f7493-6a7a-4a0d-9948-a151a46d27f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>b76d5dea-7869-4909-82c3-0c2866a4af3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip941845</value>
      <webElementGuid>307970d6-8647-4320-8db8-027c9146dcb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view_mapel&quot;)/div[@class=&quot;card px-2 py-3 mt-4 fs-poppins&quot;]/div[@class=&quot;row mx-n1 mt-3&quot;]/div[@class=&quot;col-md-12&quot;]/table[@class=&quot;table table-striped table-hover row-border order-column dataTable&quot;]/tbody[1]/tr[3]/td[4]/a[@class=&quot;btn btn-light btn-sm waves-effect waves-light&quot;]</value>
      <webElementGuid>b00b6810-d729-4bf5-9041-e8db2dd6b14d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_mapel']/div/div/div/table/tbody/tr[3]/td[4]/a</value>
      <webElementGuid>f0ad5031-0bb1-4468-86e8-e13ddf3d648e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='praktik'])[3]/following::a[1]</value>
      <webElementGuid>27e4fea7-fecf-49b4-9e09-1e15e5051351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='teori'])[3]/following::a[1]</value>
      <webElementGuid>e6772f5d-3587-4a72-b526-bd04a74fba6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MP-014 - Penuntutan'])[1]/preceding::a[1]</value>
      <webElementGuid>0376eca9-36a7-4ddf-8d91-db0b90440ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[4]/preceding::a[1]</value>
      <webElementGuid>9efdf32d-a511-4048-885d-582d255f5895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://101.255.121.243:1180/classroom/scores/lesson/57/12']</value>
      <webElementGuid>c3bb402b-667f-4841-b5c5-c34d9ed31d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/a</value>
      <webElementGuid>d02cb6b5-9684-4897-8962-374a0c39fd66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://101.255.121.243:1180/classroom/scores/lesson/57/12']</value>
      <webElementGuid>b17ed7ac-a4f4-441d-bd5f-102b2b44022a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
