<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_102550100</name>
   <tag></tag>
   <elementGuidId>608af1d4-546d-401f-8548-3b45d2148013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;DataTables_Table_0_length&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='DataTables_Table_0_length']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2fc216f8-033d-4d3a-8cd8-e327e87c498f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DataTables_Table_0_length</value>
      <webElementGuid>892d4fa5-d2c4-4b70-bc63-49ff3f129519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>DataTables_Table_0</value>
      <webElementGuid>4b1d6a67-084c-4b2b-b278-0959dc732b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-select-sm</value>
      <webElementGuid>0836866c-2841-4e28-a0ca-761bd09649fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>102550100</value>
      <webElementGuid>c624c8c1-e73c-438a-b497-2d08275cd066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0_length&quot;)/label[1]/select[@class=&quot;form-select form-select-sm&quot;]</value>
      <webElementGuid>9250d5b2-5779-4504-a8a5-b785855e30ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='DataTables_Table_0_length']</value>
      <webElementGuid>7ff6da9e-7f33-46d2-87b2-5c2119f21260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DataTables_Table_0_length']/label/select</value>
      <webElementGuid>8632bb10-c6f7-4c89-bbfb-4006bb71cba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SD'])[1]/following::select[1]</value>
      <webElementGuid>77aa1ec6-1f06-4e66-abdf-fd5848f0a1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries (filtered from 14 total entries)'])[1]/preceding::select[1]</value>
      <webElementGuid>89d56351-3f6f-4b17-a1e5-3b297222daf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Widyaiswara'])[3]/preceding::select[1]</value>
      <webElementGuid>42541942-a491-44f5-914f-0ccdc7514cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>085b8890-195a-4780-8631-587210795d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'DataTables_Table_0_length' and (text() = '102550100' or . = '102550100')]</value>
      <webElementGuid>ee98e793-d43f-4b59-9e66-0b816a795c25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
