<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Rekening_account_number</name>
   <tag></tag>
   <elementGuidId>a20073d3-45ba-4a13-a54b-1ed4f1125a8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a471f18f-95d0-4dea-9f80-4e1157ecb0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>262a432c-07e9-44db-a472-0e86a59b40f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>51953c1e-b9d7-41de-a0ea-a03a5451e32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ( isNaN( String.fromCharCode(event.keyCode) )) return false;</value>
      <webElementGuid>3adcb779-d121-412d-836b-f9aaa85cee9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account_number</value>
      <webElementGuid>ce60bfc2-7684-42c1-a7b5-01485ef50720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account_number</value>
      <webElementGuid>0ed3a265-d6c2-4805-91c7-9d3a9bcde455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Rekening</value>
      <webElementGuid>254448de-2bc8-416b-a148-cec980a625ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account_number&quot;)</value>
      <webElementGuid>f7af09cb-45de-4c79-b2e9-d7e051c623e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account_number']</value>
      <webElementGuid>0a1a4b82-4f79-4a01-ae90-7359ba6fe2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_user_data']/fieldset/div/div/div/div[15]/div/input</value>
      <webElementGuid>c6d3ca14-1c39-4791-aad5-b7c5f6fc614c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/input</value>
      <webElementGuid>169cd498-42f1-49e9-b382-b03b8adab744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'account_number' and @name = 'account_number' and @placeholder = 'No Rekening']</value>
      <webElementGuid>ff61ae6e-e4ea-4c3a-a0b8-8190973afbdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
