<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_user_dob</name>
   <tag></tag>
   <elementGuidId>24245e16-a18d-431b-9876-60af50c4d6a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_dob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_dob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a35931fe-ca2e-4bf7-bc33-4161f54a128c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>550b1f4f-d8d5-4f92-af18-83a97a037ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker</value>
      <webElementGuid>d4ff2285-9187-4fb2-af65-d561fc236e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_dob</value>
      <webElementGuid>267cfee4-afcd-4c62-a6be-71d158ac8480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_dob</value>
      <webElementGuid>f1ebd995-1753-43e0-8969-38a84359704e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>aa7cdcb0-9d79-415a-95fc-23f7f541394f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>b9f6c742-c556-4abe-9de5-9b221b858240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_dob&quot;)</value>
      <webElementGuid>d4d13eb3-1096-41f6-97d3-e309ebada20f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_dob']</value>
      <webElementGuid>520ebc05-654c-40f4-beba-c7f30ffeb3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_user_data']/fieldset/div/div/div/div[6]/div[2]/input</value>
      <webElementGuid>cb71ce7d-75f1-440a-94b0-ff59eba193c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>2f9ef5ac-5d8b-4c9c-80ee-d60b36c0fd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'user_dob' and @name = 'user_dob' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>512c74d0-8ca6-40f9-a286-50a1b3c03526</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
