<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_emp_position pangkat</name>
   <tag></tag>
   <elementGuidId>fa350934-3d1c-490d-bdd9-78bc4ce34628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emp_position</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emp_position']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af304f05-c975-4da9-afdd-f9cf19e0251a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04436537-bdb3-4af3-b870-14a455eda30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f738625a-8f2a-4d76-b183-08473fe1192d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emp_position</value>
      <webElementGuid>2ad51aee-6fd6-443a-a1c2-5705414c8db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emp_position</value>
      <webElementGuid>3f6b2342-a709-4591-a502-3553f8578c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi Jabatan</value>
      <webElementGuid>fc3ae010-5991-4783-9d7a-c10c01ec93f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emp_position&quot;)</value>
      <webElementGuid>bec31d6b-a0b5-41ce-b7bb-d08549230db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emp_position']</value>
      <webElementGuid>13b6bdc2-fee6-42fc-a340-ddb8bb02f32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employee_data']/div[3]/div/div/input</value>
      <webElementGuid>ee68e71c-6534-44d1-9073-589b96877cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>fa1cf1de-626c-4951-94de-3345957497ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'emp_position' and @name = 'emp_position' and @placeholder = 'Isi Jabatan']</value>
      <webElementGuid>3bbce4af-6576-4ef3-b98c-5279c05f7f96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
