<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Angkatan_user_batch</name>
   <tag></tag>
   <elementGuidId>6fd3e3c5-3ad8-4e2d-bf25-9690a2ed8489</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_batch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_batch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecb530c5-7fff-455d-ac07-f0b86a220c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c30c05f6-a3bb-446f-b643-3bff3176c00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>933a5e8d-0b7e-41ad-98fc-e4818395bf41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e9fd4a85-da4e-4373-a281-6aea72d160d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_batch</value>
      <webElementGuid>c77b1fb1-984d-4fd3-9c9e-0af3e82ea82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_batch</value>
      <webElementGuid>c7d12ad0-645a-41ad-a2e1-840ac38303dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Angkatan</value>
      <webElementGuid>dcf535d4-965b-43d2-b6cb-f86122fac437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_batch&quot;)</value>
      <webElementGuid>a55c2f45-da49-498a-b5f1-98c334cf61fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_batch']</value>
      <webElementGuid>f72fea32-3c1a-44e3-ade6-240a90b93197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_user_data']/fieldset/div/div/div/div[13]/div/input</value>
      <webElementGuid>1965f407-6272-41e3-86b3-75b087ba3c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/input</value>
      <webElementGuid>e1bdfc62-8b00-4320-8c57-ca53cd3c41be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'user_batch' and @name = 'user_batch' and @placeholder = 'Angkatan']</value>
      <webElementGuid>ec3720ba-887e-435a-b0d2-ce6837947e78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
