<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TMT_job_start</name>
   <tag></tag>
   <elementGuidId>6618d0bc-bb8f-456e-937d-de6cb3288d2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#job_start</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='job_start']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55dc1761-8d27-4694-b5b5-355ff72d7796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a95e5dcf-99e3-43ad-a3c9-c11dde7ded73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker</value>
      <webElementGuid>843393f9-885c-4c40-9f96-846996601b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_start</value>
      <webElementGuid>3ecb2b19-7d7c-43f2-a52d-d241b7875564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job_start</value>
      <webElementGuid>33c5183c-4c2d-4d23-ab9b-ed9e5f82733b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>TMT</value>
      <webElementGuid>795219b3-6a01-4116-8c2e-a47ef98ecb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>febccb6d-5c9a-4384-8f0c-969a9064fc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_start&quot;)</value>
      <webElementGuid>89c4e70e-ec4b-45ca-b5d2-4743352d96b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='job_start']</value>
      <webElementGuid>61f4192f-c7bc-4399-af4a-8a0236cc9534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_user_data']/fieldset/div/div/div/div[12]/div/input</value>
      <webElementGuid>e900b6a2-1998-4941-a474-dc8635c0d99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/input</value>
      <webElementGuid>b15857d2-bdd0-4cac-84f8-ea38d81e33b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'job_start' and @name = 'job_start' and @placeholder = 'TMT']</value>
      <webElementGuid>0c09cce3-8e4e-4d9d-8688-939c3309dab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
