<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_user_pob</name>
   <tag></tag>
   <elementGuidId>184d78da-328e-4361-82e5-54662b899bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_pob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_pob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f75fff0-160a-4729-8b56-418519ab10d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e5ba543-61f4-49dc-ae33-0aba5e7d1f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8f86baae-a061-4c5e-a58f-b62b9d5da206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_pob</value>
      <webElementGuid>edd669f6-837b-4462-8740-87a8c5aeff55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_pob</value>
      <webElementGuid>2421ddb4-51af-4cd8-81af-c1d2d25ae924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tempat Lahir</value>
      <webElementGuid>20b62ad8-05b2-4071-b246-be97829b2010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_pob&quot;)</value>
      <webElementGuid>2ac528aa-69c2-4c97-a84c-6c0b864a650a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_pob']</value>
      <webElementGuid>6119489a-874f-4a01-a838-5dee0678109c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_user_data']/fieldset/div/div/div/div[6]/div/input</value>
      <webElementGuid>226cbc35-e2a1-49d8-b062-ba4269ebf5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>189685e3-1cc6-4d44-85fe-5a5e6f0a8094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'user_pob' and @name = 'user_pob' and @placeholder = 'Tempat Lahir']</value>
      <webElementGuid>af413f82-7d76-4cdf-8d6c-5f7dfd69807a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
