<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_user_hp</name>
   <tag></tag>
   <elementGuidId>0b6ef909-7ca2-411a-9cbe-d4d6a22951b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_hp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_hp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c75db48f-bc43-44c7-b43e-db324021db5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7818a336-a42a-47fd-8567-16116267cacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5b106bb0-36bc-439d-8368-b216a804b335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_hp</value>
      <webElementGuid>c34fbc11-60cc-4017-9580-13f5981e0e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_hp</value>
      <webElementGuid>4923e9bb-aeae-49db-ac06-b1e56df098c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ( isNaN( String.fromCharCode(event.keyCode) )) return false;</value>
      <webElementGuid>e73667b6-d3c0-4e3f-a287-acad92bf0b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Handphone</value>
      <webElementGuid>3ad3c96f-6b67-4397-bde1-39a10ea6d5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_hp&quot;)</value>
      <webElementGuid>b670d5fd-562c-4c5f-81c2-0dd78fbaf3d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_hp']</value>
      <webElementGuid>7e4fbfb0-39dc-4553-9c1c-bceb83449134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_user_data']/fieldset/div/div/div/div[10]/div[2]/input</value>
      <webElementGuid>630d9e98-0107-41a4-aea0-dc19b68676e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/input</value>
      <webElementGuid>3dc4b0a2-bb26-4803-81cc-48335c3b3cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'user_hp' and @name = 'user_hp' and @placeholder = 'No Handphone']</value>
      <webElementGuid>ae3bfcc0-38e6-4a59-8b7f-b9e42e5a14a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
