<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Satker</name>
   <tag></tag>
   <elementGuidId>69a895ea-e190-40f1-972b-e1b2317dc773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-riu_id-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-riu_id-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8abf7974-6f9f-4818-b674-e4e0cf643786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ef2a22b2-b1d4-4395-892b-dd4240a46358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-riu_id-container</value>
      <webElementGuid>19181b3d-fa8f-49cb-a4a5-05e6b3a83299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>5c82af08-a00b-4d5e-b7bb-c454df2a80c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2f999e42-418f-4ad5-8c4d-31ed22d5e479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Satker</value>
      <webElementGuid>185980ec-7df6-46c9-9829-bb3f672d2d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-riu_id-container&quot;)</value>
      <webElementGuid>0ab16f2c-23c9-4a28-99b7-6cd65db98239</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-riu_id-container']</value>
      <webElementGuid>02857da4-4c59-4e46-9ff1-bb3bfe1ef166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employee_data']/div[4]/div/span/span/span/span</value>
      <webElementGuid>e52709a4-1ec3-46fa-8b66-0a51968a2821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[12]/following::span[4]</value>
      <webElementGuid>ec0f29a0-0483-44bd-8ec1-c26ea758f99b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Pengguna'])[1]/preceding::span[4]</value>
      <webElementGuid>b506d4c0-0307-45c9-bbd4-187f4b5318e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span/span</value>
      <webElementGuid>3ec8b24a-7a06-4aff-b7f1-6b8e1dcf55d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-riu_id-container' and (text() = 'Pilih Satker' or . = 'Pilih Satker')]</value>
      <webElementGuid>57cd994c-2571-439c-9f0b-8de47a47318b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
