<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_C-02 - Kelas II_btn btn-light btn-sm no-b_5249a2_1_2</name>
   <tag></tag>
   <elementGuidId>db68cbc6-b605-4992-a8bd-46ee31c1ef4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[10]/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7e91348-840c-4d8e-ad1e-8f622f42aeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light btn-sm no-button no-shadow</value>
      <webElementGuid>31ae8ee9-82fe-4332-a480-e65e0d5f8d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://101.255.121.243:1180/classroom/presence/learning-module/2/7</value>
      <webElementGuid>b5dc8a51-2682-4c3d-8d5c-7f08f6366c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>dd98a14b-b5d2-4bed-b275-98b72f222630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>ad8ca54e-cd13-428a-9bd5-3eb1c77f415a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Kehadiran</value>
      <webElementGuid>0c6b7d29-4ac3-4da1-98d9-3728da9e2946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Kehadiran</value>
      <webElementGuid>4014c39c-5601-47f4-9211-100c379b1762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip753715</value>
      <webElementGuid>0341203f-1403-46f7-8097-3b78372673a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[10]/a[@class=&quot;btn btn-light btn-sm no-button no-shadow&quot;]</value>
      <webElementGuid>393df3ea-f7c1-4a4e-b654-f04df1e625c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[10]/a[4]</value>
      <webElementGuid>722eb320-e1da-40c7-996a-024d5a8a4b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C-02 - Kelas II'])[1]/following::a[4]</value>
      <webElementGuid>0a2cd8a7-ca47-43bf-9c35-98c326d7e653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusdiklat Mapim'])[1]/following::a[4]</value>
      <webElementGuid>070c37ad-a43c-4b8d-8477-7fd0002a9af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MP-001 - Agama dan Budi Pekerti'])[2]/preceding::a[1]</value>
      <webElementGuid>319680df-517c-46d6-b895-a17577dca52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAPIM'])[2]/preceding::a[1]</value>
      <webElementGuid>df4adc14-3dc0-495f-bf32-a849459d7eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://101.255.121.243:1180/classroom/presence/learning-module/2/7']</value>
      <webElementGuid>48a94b66-4090-499b-b31a-7743539e6c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>da50093c-9c5d-4f1e-9b4a-d2041c47990f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://101.255.121.243:1180/classroom/presence/learning-module/2/7']</value>
      <webElementGuid>0ac073f1-b521-4d20-a3ed-b00cd92fd65f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
