<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Fungsi_material_description</name>
   <tag></tag>
   <elementGuidId>d323b2c2-1056-4df0-b17a-065132047aef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='material_description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#material_description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>986c3d17-6018-4e4c-8bf9-e725ac219e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ca03c1dd-bebc-4081-b249-7ce321e18943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>fb2ec6cf-1b3d-492e-8ce6-10e8d6346904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>material_description[]</value>
      <webElementGuid>1bac942f-a828-4c5b-b2f8-c2922cbdaece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>material_description</value>
      <webElementGuid>d3c66be1-41b6-4901-9769-f58fbccc90ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;material_description&quot;)</value>
      <webElementGuid>937bd241-3b6e-4f2e-b8f4-fe8c93116588</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='material_description']</value>
      <webElementGuid>38d31b93-740b-4252-8238-58c3c89cf1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableWrapper']/tbody/tr/td[3]/textarea</value>
      <webElementGuid>664cdbfc-ad72-4cac-90d0-2e3d265f3fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/textarea</value>
      <webElementGuid>bf8209b4-ddd5-42b8-8739-f1c1493ed886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'material_description[]' and @id = 'material_description']</value>
      <webElementGuid>a7b57e54-b173-41da-bbe7-4b51299014a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
