<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Terbatas_examination_duration</name>
   <tag></tag>
   <elementGuidId>d59ae98a-1598-483d-83a8-126aa305e241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='examination_duration']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#examination_duration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4126b3b8-0a56-45cb-9dbc-09c322fc43b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>456408db-f9cd-44b0-9776-805c274cb194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control examination_duration</value>
      <webElementGuid>215f0922-e0b4-44c2-bbed-4c5781763d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>examination_duration</value>
      <webElementGuid>4b5814f0-9ad4-40fb-b54d-c0356048222c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>examination_duration</value>
      <webElementGuid>491a1a28-bb7c-4608-ae74-aa238ad9af63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>2e26dff4-cd17-49d3-82ee-defe2d8d68dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bc1ed501-3bae-4bfa-963b-a6999bf46f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5449b44c-e00c-4baf-8bcc-e4c60d768179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;examination_duration&quot;)</value>
      <webElementGuid>cbffd20e-c990-492b-9d0a-3eed8ba2beb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='examination_duration']</value>
      <webElementGuid>d81daa7b-3cc9-479b-aaaf-3c9f3ecbb013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-minute']/div/input[2]</value>
      <webElementGuid>5b837553-f354-48bd-8286-77cfd3fed554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>63263a3c-964b-4b85-aaeb-b35163e36e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'examination_duration' and @id = 'examination_duration' and @placeholder = '0']</value>
      <webElementGuid>867d00d7-a003-4111-a8dc-9805608e98c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
