<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_course_code duplicate</name>
   <tag></tag>
   <elementGuidId>dc9b7c8b-ace0-49cc-821c-4d134f722256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='course_code'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f1-duplicate > div.card-body.p-0 > div.mb-3 > #course_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdf6cc00-121e-4223-8517-00d34457f578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4170138-f16c-48cd-9b4c-2026539807b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>course_code</value>
      <webElementGuid>1b17ebb4-51b7-42b5-bd79-ce2df954533e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>course_code</value>
      <webElementGuid>f1bb1861-9ff4-466a-808c-9f921c736e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b25f13d3-1e03-42da-9f68-94a173d5282d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi Kode Diklat</value>
      <webElementGuid>4829ade6-64f8-4935-bb03-5747f245a8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c74a06a0-07db-4b9d-b8b8-31b845723212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f1-duplicate&quot;)/div[@class=&quot;card-body p-0&quot;]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;course_code&quot;]</value>
      <webElementGuid>14de322e-af5a-4f74-8ed6-6cbf76dc4874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='course_code'])[2]</value>
      <webElementGuid>fa9a4298-ff3e-4fc6-add8-9a17ae860d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1-duplicate']/div/div/input</value>
      <webElementGuid>12940b57-f3a5-4e4a-a0d8-a23f3b19cba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>b441b1d4-daa5-4c93-91e4-c8ba7c52db45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'course_code' and @id = 'course_code' and @placeholder = 'Isi Kode Diklat']</value>
      <webElementGuid>4c20d829-b5f4-4045-9e78-beb443fd8280</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
