<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pusdiklat Mapim_btn btn-light btn-sm no-b_164737</name>
   <tag></tag>
   <elementGuidId>8bf3a5f7-e86b-4810-815f-5a7e2eb6626b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='doView(this)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-light.btn-sm.no-button.no-shadow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe1ff742-d233-4d51-a2bd-e086d1b40b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light btn-sm no-button no-shadow</value>
      <webElementGuid>0fa815ae-8f00-477e-9e39-1c433ffd20dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>doView(this)</value>
      <webElementGuid>2dc2ddbc-1690-4d89-b599-316df8e1955f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>46</value>
      <webElementGuid>f7c59c91-6a1a-4727-898a-3468780fa1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>b9f1f10a-d477-48f5-af6c-a4cf96d33816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>f1bb2121-b8df-4c7c-8e80-6237b7888890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Lihat</value>
      <webElementGuid>d72e2e12-fb3c-41cf-b846-0aca8e4f556a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip703894</value>
      <webElementGuid>f3c98be5-373d-4d85-961a-46c551ef6061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[7]/a[@class=&quot;btn btn-light btn-sm no-button no-shadow&quot;]</value>
      <webElementGuid>b848cd8b-5a3a-44e9-9f1c-4e2a811d4ee0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='doView(this)']</value>
      <webElementGuid>779c1501-1564-43c0-8c57-99698cc2ffab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[7]/a</value>
      <webElementGuid>714d5f9f-78fa-4c37-9929-ac2c95df942e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusdiklat Mapim'])[2]/following::a[1]</value>
      <webElementGuid>bf42e055-d33f-43b1-aa01-ee4fd0a05376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PPPJ GELOMBANG II TAHUN 2016 - Kelas 2'])[2]/following::a[1]</value>
      <webElementGuid>ad239e88-ef44-4b2b-b982-08850075e45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries (filtered from 11 total entries)'])[1]/preceding::a[1]</value>
      <webElementGuid>acd2dd77-fb57-4e6e-ad98-9b05a498679f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
      <webElementGuid>f7c358fa-1038-4218-ab72-cffdd753008e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
