<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_lesson_duration</name>
   <tag></tag>
   <elementGuidId>26024ea1-7fe5-4afc-80e3-4e1ed0d4b5cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lesson_duration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson_duration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b679adc0-e01e-48b6-be91-ae37ce8d7a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5041f9e5-cc79-4d99-9766-e4823dd7d4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson_duration</value>
      <webElementGuid>e2137cca-18a3-4268-a98e-b9fba999c802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson_duration</value>
      <webElementGuid>a924e276-e731-43b6-83c8-68afd2a27c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9fc4da66-43a6-4684-b4ac-83bde15c995c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah Jam Pelajaran</value>
      <webElementGuid>399b1b9f-98b9-45f3-a0c0-9f046dbbbf64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>5b68516f-0183-440e-9606-8c8d679abccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson_duration&quot;)</value>
      <webElementGuid>f41f74cf-d0c2-4763-90e2-d334128330f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson_duration']</value>
      <webElementGuid>fa4830b8-146a-4f41-9c81-75d6355b041c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[5]/div[2]/div/div/input</value>
      <webElementGuid>1a2233b6-31d5-438e-a218-8aa22213052e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>7c5e1356-f541-4055-a592-bb9e313d2100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'lesson_duration' and @id = 'lesson_duration' and @placeholder = 'Jumlah Jam Pelajaran']</value>
      <webElementGuid>a3bc052d-eaf7-4487-962d-19705469c164</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
