<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_lesson_per_hours</name>
   <tag></tag>
   <elementGuidId>619d10a1-fc75-45e8-a6bd-c787055b5c5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lesson_per_hours</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson_per_hours']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31856e51-c440-44ae-bd65-2c69ad9a71d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5860132f-485f-4593-b796-3ec7df044430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson_per_hours</value>
      <webElementGuid>d1b05f89-45fc-4585-ab8a-aa8c1ceabc42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson_per_hours</value>
      <webElementGuid>5be976fe-e606-4dac-a133-0b59f2f564b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5e442c6a-f798-4c1e-94c7-d488dc726c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Durasi 1 Jam Pelajaran</value>
      <webElementGuid>9fd2c737-f1d5-44ae-9bb2-603ead3d716f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2217db30-14bc-453b-8cdf-b117c7fafe10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson_per_hours&quot;)</value>
      <webElementGuid>535e83ec-dad3-47bb-ab16-0c59a24a4735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson_per_hours']</value>
      <webElementGuid>2ee3ffc7-a431-4826-822c-b8acf2940736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[5]/div[3]/div/div/input</value>
      <webElementGuid>2fd2e31a-05fb-4a78-aad1-5d92c8b838fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>a028bc02-761c-4bc5-8ac7-a71ac2402397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'lesson_per_hours' and @id = 'lesson_per_hours' and @placeholder = 'Durasi 1 Jam Pelajaran']</value>
      <webElementGuid>0afe6351-a95e-47ea-8113-74eee5d5eed3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
