<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mampang Prapatan_btn btn-light btn-sm no-_2f860f</name>
   <tag></tag>
   <elementGuidId>f7828a11-b85d-4be5-bca4-4906007fd68b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-light.btn-sm.no-button.no-shadow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c0cccd1-36d3-4f3b-8022-244a708a5c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light btn-sm no-button no-shadow</value>
      <webElementGuid>dab7d749-f0ed-4d7d-98f8-b8d295d802d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://103.253.107.18:24400/master/educationunit/update/38</value>
      <webElementGuid>65ce3445-de29-4ce3-a31e-96e99e5ed903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ubah</value>
      <webElementGuid>5106b228-8bb8-4b76-a697-bffa05c9852c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[5]/a[@class=&quot;btn btn-light btn-sm no-button no-shadow&quot;]</value>
      <webElementGuid>d27388d6-ef11-43e7-afed-f3d16fda0b7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[5]/a</value>
      <webElementGuid>d9ea645e-f692-4a08-914b-d7b79a30009d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mampang Prapatan'])[1]/following::a[1]</value>
      <webElementGuid>a9e6f4ad-ba78-4be8-92e3-7325dc3926cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusdiklat SDS'])[1]/following::a[1]</value>
      <webElementGuid>c4ccbe75-3087-49cf-9ee8-024bde48d7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries (filtered from 4 total entries)'])[1]/preceding::a[1]</value>
      <webElementGuid>af49a15e-931d-4a40-a5d8-5abe20eae529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://103.253.107.18:24400/master/educationunit/update/38']</value>
      <webElementGuid>33412a0d-13fc-447e-9a98-a94264f093e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>aa48eb51-d30c-40f5-9f85-6e8b0b6cc424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://103.253.107.18:24400/master/educationunit/update/38' and @title = 'Ubah']</value>
      <webElementGuid>19c02d05-5405-40a0-8784-8a9bb2d2af5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
