<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_unit_name</name>
   <tag></tag>
   <elementGuidId>aaeffa33-d258-4b14-af77-951704089a43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unit_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unit_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2376a591-8472-4806-8766-745d15707981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c1d6773-0370-455a-b7af-ab82125d32cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unit_name</value>
      <webElementGuid>ce027fb3-1f9b-47c1-a361-206af8b034f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unit_name</value>
      <webElementGuid>a5f66166-883a-46dd-bf38-cd5732872cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>766c4650-3340-4579-9f01-ebe052b37e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cebb64da-ab9a-4c28-9fd4-7bd8d57327ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Satdik</value>
      <webElementGuid>059fa48c-7ff4-42ca-91c6-28fba08051a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unit_name&quot;)</value>
      <webElementGuid>96da1f3c-2a1f-4f63-b796-c3cb1564d2b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unit_name']</value>
      <webElementGuid>02cffe1b-ff36-4b89-a249-dfddde26a7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[2]/input</value>
      <webElementGuid>8fd3c6c8-7aaa-4555-881a-cd7a80574436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>be45e201-4d43-4942-8d03-8dd99effa2ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'unit_name' and @id = 'unit_name' and @placeholder = 'Nama Satdik']</value>
      <webElementGuid>c7a5fbe2-58a1-48de-b79a-e92864b45388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
