<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Terbatas_examination_duration</name>
   <tag></tag>
   <elementGuidId>483f677f-175b-488f-a440-cc7fcf9eb15e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#examination_duration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='examination_duration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>572caea0-53e0-4cea-84b0-0ca757bd6aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2ec3e4e-4595-49c7-ad03-d1b3f3ed7bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control examination_duration</value>
      <webElementGuid>cc69f799-0d78-48a7-8b9b-e037b4cfc711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>examination_duration</value>
      <webElementGuid>5d320ac0-0003-48da-997c-7ce882c2795a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>examination_duration</value>
      <webElementGuid>a211e676-78c9-4c03-9056-aae74fdf3f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>da955d4c-a2df-48da-a5f4-6a3498bdf5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>007629a9-9ed8-4852-98e3-0c787fc4c509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;examination_duration&quot;)</value>
      <webElementGuid>5b259ecd-36db-44c8-a2af-472fd13870b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='examination_duration']</value>
      <webElementGuid>587a3d6e-a95c-4231-b62d-7b66ffd41ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-minute']/div/input[2]</value>
      <webElementGuid>a07a7a60-b3db-4847-8ef8-83e8bb9756c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>d54e6df0-aede-42d1-b8b4-a3632e588cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'examination_duration' and @id = 'examination_duration' and @placeholder = '0']</value>
      <webElementGuid>b5677c92-42e4-47c8-b07f-9df8f4e9e65e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
