<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_is_random</name>
   <tag></tag>
   <elementGuidId>fc253216-5e83-4a6e-9a57-362d322e7709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#is_random</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='is_random']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71e440f1-a773-49f9-95df-5afcad0b8877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5c258ddc-a04b-4d90-b5f2-0d179891e703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>70e6122e-d445-47e1-a639-51642b1e37a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_random</value>
      <webElementGuid>eb69abcf-d1b7-4b9a-8fc6-841b2b0772a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_random</value>
      <webElementGuid>b430468c-62b3-4318-84cf-b71a4a954887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is_random&quot;)</value>
      <webElementGuid>78bef549-a780-41b8-9a69-df606c3affba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='is_random']</value>
      <webElementGuid>186a7309-64aa-4f26-8bed-1258a121756f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[4]/div[3]/div/input</value>
      <webElementGuid>3071dd77-fec4-44c7-b8fe-8ec863986445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>dd5a75de-5a9a-4d72-aa07-c141c94f358d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_random' and @id = 'is_random']</value>
      <webElementGuid>ddf3cb5e-41e3-4307-b439-659b30e91e78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
