<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_section_order</name>
   <tag></tag>
   <elementGuidId>fc5a243d-d2a9-4309-9066-3b3804399199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#section_order</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='section_order']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3bedd6d8-7613-45f6-a65d-1535d0a0e8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8f7155c4-11f0-4977-b619-87e7c67a5aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e848fd7b-17d1-4e93-8dec-e2c5217a952b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>section_order</value>
      <webElementGuid>507e7249-5ec9-4538-bddc-f8e29e1bb2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>section_order</value>
      <webElementGuid>2f677b5a-874b-4f79-884f-1d86bf0ea88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Urutan</value>
      <webElementGuid>79eca9ea-5ffd-4f44-aa0a-05d3ae9b7cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section_order&quot;)</value>
      <webElementGuid>863e2a79-1955-4ba6-8268-9805f2ef120b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='section_order']</value>
      <webElementGuid>73e99984-009b-49e9-96e1-ea23018ed9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[2]/input</value>
      <webElementGuid>16c4b9f6-2cd1-4521-8d75-5015ea7b98a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c3dfe382-bfe3-488f-9aa1-ff6ef4390d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'section_order' and @id = 'section_order' and @placeholder = 'Urutan']</value>
      <webElementGuid>fa8fe7be-f902-4fa6-9fe7-0e480ad61253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
