<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_go_to_prev_page</name>
   <tag></tag>
   <elementGuidId>10bd66cc-f20b-4cf3-86a7-480c68893a8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#go_to_prev_page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='go_to_prev_page']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e5e08f5-1ee4-464b-aa00-b0974926df90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>369c373e-ee49-49c6-b10d-bc695dd3accb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>8e4ddfff-07ce-4a86-a261-4ecc15677c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>go_to_prev_page</value>
      <webElementGuid>2e19fa77-fc67-41e2-8f50-8fad7edea404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go_to_prev_page</value>
      <webElementGuid>267358a2-6a63-4cf8-abed-3a3ee58d0c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go_to_prev_page&quot;)</value>
      <webElementGuid>ca75aa93-b21e-476e-a7e4-ff063c354133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='go_to_prev_page']</value>
      <webElementGuid>2291f5fd-8ca4-41b8-9194-4555f6bdab72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[6]/div/div[2]/div/input</value>
      <webElementGuid>7b75442f-5102-4634-85e7-5f7e0680f110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/input</value>
      <webElementGuid>d51a2cf9-cb00-4f24-b11a-d04e8c47643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'go_to_prev_page' and @id = 'go_to_prev_page']</value>
      <webElementGuid>b20bd22b-b71b-4994-a22e-46a3d1f388eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
