<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_section_duration</name>
   <tag></tag>
   <elementGuidId>3f6ebc5a-118f-4206-9016-ecd076c2ecc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#section_duration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='section_duration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7bd721a3-6d6b-41cc-91b9-db063a907f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>775cb75b-7cae-426e-b668-d2d447c9f686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>22b61658-4e67-429d-b2a3-e505d54a768e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>section_duration</value>
      <webElementGuid>219f96ff-d7db-4859-b4cb-818d9f318164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>section_duration</value>
      <webElementGuid>70169453-d910-4f87-977e-e5c79f668e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fc7935c9-52fb-4f23-9d6c-2f28999b368e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>08021804-3628-4c9f-803d-ae1a1d6af485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section_duration&quot;)</value>
      <webElementGuid>2317e273-c594-4978-b1ea-4596d6e96d23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='section_duration']</value>
      <webElementGuid>272d16dc-1141-46c3-b4b8-04c339a85150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-section-duration']/div/div/input[2]</value>
      <webElementGuid>f2eec6f5-5489-4131-9cb0-16533a65c862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input[2]</value>
      <webElementGuid>edafe656-56ce-41b9-a27d-88dadbb75824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'section_duration' and @id = 'section_duration' and @placeholder = '0']</value>
      <webElementGuid>84aadfcb-41c6-429c-bb58-3aef6f37c096</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
