<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contoh Soal_is_mandatory</name>
   <tag></tag>
   <elementGuidId>d6ef232f-37fc-4fed-9461-b01b1d0aec12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#is_mandatory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='is_mandatory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ad76b82-cba8-42b4-9373-a89ae749595c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>9b163f56-3e18-4e24-827b-dfc626c6b02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dac5187f-b047-4110-bd09-b975751f1eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_mandatory</value>
      <webElementGuid>d329a57c-bfaa-4a62-86a8-8208c4ab3842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_mandatory</value>
      <webElementGuid>d0138d40-f544-4bf6-85f1-6e08e7b2d952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>14b186b4-28e5-460b-b9ff-f2e5dea815a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is_mandatory&quot;)</value>
      <webElementGuid>47a96b45-7a77-442a-bead-4946d582c988</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='is_mandatory']</value>
      <webElementGuid>733a147e-b5d4-4006-a956-6f9092f3b284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_is_mandatory']/input</value>
      <webElementGuid>1b946bdc-5dfe-423f-87de-800b2c9adadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6e555269-107a-419f-a01d-82e6eb5cc053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_mandatory' and @id = 'is_mandatory']</value>
      <webElementGuid>1972687c-1db2-4597-a7f1-ec4621731143</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
