<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_()_examination_description</name>
   <tag></tag>
   <elementGuidId>c34ef598-34b5-47f9-8bd4-f3e0336d560e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#examination_description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='examination_description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0efa4d9d-50a8-450a-a601-dae07cedfca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>examination_description</value>
      <webElementGuid>f49e4680-4795-461f-a2c9-c1e51fb3cc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>examination_description</value>
      <webElementGuid>30b77bc9-e9e2-417f-95e8-f02fe66ee85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>bdacb80e-1a38-4c00-876d-e879296f2aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b78b1cea-af31-493c-9fb6-f491ced75c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Deskripsi</value>
      <webElementGuid>f5a30ce4-77f3-484f-a0aa-584b1d20c020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;examination_description&quot;)</value>
      <webElementGuid>a286059e-a0bf-4a62-8681-246275f0cd7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='examination_description']</value>
      <webElementGuid>709a71cc-4842-482e-ba98-e33dfff6a99b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[4]/textarea</value>
      <webElementGuid>adb04447-82dc-4f07-a8ca-0eb85e99f79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>7924aec7-314a-4b02-aad2-63b5e66ae347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'examination_description' and @id = 'examination_description' and @placeholder = 'Deskripsi']</value>
      <webElementGuid>6fd98107-5c35-4e19-bec7-6c832d8d58b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
