<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank Soal_tableSearch</name>
   <tag></tag>
   <elementGuidId>73036aae-837f-4b49-9c68-a715e5d7b763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tableSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tableSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d11ebffa-6882-4686-bfd3-1925e475ac2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca6b84a5-cace-4f37-ba7d-6bb20fa84ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tableSearch</value>
      <webElementGuid>3a7c5d8a-5694-40d5-bfaa-7425e6ba3a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>abdaf716-93a1-4097-bf70-5d1cabcd97e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pencarian...</value>
      <webElementGuid>0264b2b4-8134-4a26-b0d1-4cffb4db3be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableSearch&quot;)</value>
      <webElementGuid>4c847f9d-8c17-4f07-afc9-222666030214</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tableSearch']</value>
      <webElementGuid>475b8eb0-5fbb-4c37-8f65-246ab6c34d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_search']/div/div/div/div/input</value>
      <webElementGuid>654075a9-ed2a-4021-82b6-ed1804712be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>6c316ae0-2ace-48ab-ad33-155bb3deea78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tableSearch' and @placeholder = 'Pencarian...']</value>
      <webElementGuid>3dbe90d1-bdb2-4047-84c1-110a23dafc77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
