<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>02_kelas</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f8aee092-bcf7-4b3c-9f92-547985feeca0</testSuiteGuid>
   <testCaseLink>
      <guid>4eea276e-9442-4591-be6c-665c21f26a37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02_kelas/01_1_kelas fungsi tambah</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3280ddef-f785-4125-bc63-e38925f2757e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c41ea27c-f7a7-43ae-abd6-46305e463815</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02_kelas/01_2_kelas fungsi ubah dan nilai</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2b223b7-7ea6-410d-8fc7-2f158b7f9274</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee31e57d-8a7b-49d8-a542-97f2c542e810</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02_kelas/01_3_kelas fungsi ujian dan tugas</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fc8f430-7137-4d48-ae70-cba4e2f44730</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d201797-3d30-4703-b014-4ff0fbb2d2e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02_kelas/02_alumni</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f463b30-a01e-46f6-a549-9944d814b494</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79253ee6-b4eb-42a5-aea9-6a0fbf856b59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02_kelas/05_modul ajar</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ed37089-ae1d-44e9-80d5-801ef6f99a29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5fd3835d-74df-45c9-bed6-94009645b9e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02_kelas/04_kelas saya</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288dc6fc-cf05-49bc-b516-adde46c70dd6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
