<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>04_rekapitulasi</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>eb6d6a31-5902-4f22-988a-2b0804cae7d6</testSuiteGuid>
   <testCaseLink>
      <guid>2c132c1b-409f-4bc6-a3ce-93751c92d7fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04_rekapitulasi/01_rekap nilai mata pelajaran</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d7d5c30-7c76-40ba-ba0c-27f95bc2f388</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad296cd5-f644-4c2f-b1dd-bd0b8e477fc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04_rekapitulasi/02_rekap nilai diklat</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd60c2de-614d-473f-951e-d865345e98c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7c30f89-7a6c-476b-92e4-a172811a017e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04_rekapitulasi/03_nilai akhir diklat</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d211c975-3c73-45d4-b3f8-d3e2515673d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f2b119f-c96d-4d2e-a9cd-5f1d919c6b17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04_rekapitulasi/04_laporan peserta</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13f79a57-5872-41e2-831d-6f2026148cdd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f84a64be-3bb8-4d11-ab84-46e31a443654</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04_rekapitulasi/05_laporan data widyaiswara</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7a39e41-a1e7-4b81-91d8-2c3e57435ce5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10e09e52-d3de-438e-ad5c-9f8ba0f206dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04_rekapitulasi/06_rekap kelas</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0421ec3-b559-486d-b912-e7433bed88ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3087e04-c9ff-4f24-bd80-913502985380</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04_rekapitulasi/07_data kurikulum</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f4efd60-436e-4328-8377-8c5ebc20616d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21eeb998-bd91-474f-b68f-bcb236af464e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04_rekapitulasi/08_laporan kehadiran</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50882214-751d-4028-90d1-27fe085f9f42</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
