<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>05_user</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ea599ac2-5b57-4cd6-9a06-9388d09915da</testSuiteGuid>
   <testCaseLink>
      <guid>9e5d1068-1525-42dc-92db-635f2e8cf66c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05_user/01_kepala bandiklat</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9385112d-bdbe-414a-a4ef-718a5f195d18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84fa8942-77f0-4129-a75f-be02de31bf59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05_user/02_data widyaiswara</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83f087f7-4581-45c2-a311-074a958dbf7f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1647e21a-d287-4715-987b-718c42bd882b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05_user/03_data peserta</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ab28119-a80f-42de-9057-3815d6478307</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2f75801-e97f-451b-ba39-13a6b150a0c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05_user/04_administrator</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cfbbe27-8393-41af-9500-b8d828929a9c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f90d5f0-3501-4e86-8c29-6384488bc59a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05_user/05_matgaklin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffbb7843-0a17-458d-a04e-2053aadee23a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d13b95a-4a98-4d09-975e-c021505a61c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05_user/06_penyelenggara</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0946633a-e1ed-4eaa-acad-6c578ee2d475</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
