<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Skala Nilai Akademik_btn btn-light b_b20a66</name>
   <tag></tag>
   <elementGuidId>cfd07c53-67ab-45d1-9252-2027f39a60b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='delete_data(this);']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-light.btn-sm.no-button.no-shadow.delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4805a8f-df6b-4501-8061-d6128628d388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light btn-sm no-button no-shadow delete</value>
      <webElementGuid>0b89ec72-ce30-4cf5-b956-755c084b879c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>delete_data(this);</value>
      <webElementGuid>42f0b862-1f9d-4a98-ba7b-32aab16ef0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>218</value>
      <webElementGuid>fa9ea463-0058-4cd5-9311-2fea75fd7b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[4]/button[@class=&quot;btn btn-light btn-sm no-button no-shadow delete&quot;]</value>
      <webElementGuid>95247292-cf0e-4c70-b037-9aa181daf1c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='delete_data(this);']</value>
      <webElementGuid>2b122641-504c-4d8f-af87-0b63dbc4498c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[4]/button</value>
      <webElementGuid>2b7f8c9c-8327-47fd-96b6-9e0d9393da7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skala Nilai Akademik'])[1]/following::button[1]</value>
      <webElementGuid>88f78295-d9ab-435f-99c8-2ab462084da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fungsi'])[1]/following::button[1]</value>
      <webElementGuid>17e65aa9-4856-42c1-838b-61a22e8d3149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akademik'])[2]/preceding::button[1]</value>
      <webElementGuid>b613a172-ecb2-4ca7-8747-d4b13462219d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skala Nilai Akademik'])[2]/preceding::button[1]</value>
      <webElementGuid>b0621f8b-acfb-4344-b413-14f7248b7ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button</value>
      <webElementGuid>f945f6bc-0614-40b3-92b0-8607aee1b46c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
