<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_score_group_weight</name>
   <tag></tag>
   <elementGuidId>7bef7236-b8e4-405b-ab5e-407910476c11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='score_group_weight']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#score_group_weight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8424991-7d2c-4ad8-bb30-eb9000846897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b17376de-7ac4-4f42-84f6-8a947bee49d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>score_group_weight</value>
      <webElementGuid>8a065757-1664-4563-a5b7-f42c9b699c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score_group_weight</value>
      <webElementGuid>195dee3a-89a1-4cbf-bcfd-5136f949b42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c4bbd2b1-5b3b-43e9-b80f-dc6d02375c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bobot Kelompok Penilaian</value>
      <webElementGuid>e9d9d150-ac86-4a5f-84e2-946bb459c985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>fe3dceb2-21b7-45a3-9e4b-3fc3221ce698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;score_group_weight&quot;)</value>
      <webElementGuid>e6167ebd-a4aa-4d48-93dc-6846503098aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='score_group_weight']</value>
      <webElementGuid>7ee5c65f-359b-44f4-8356-ac44dd6e1ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_score_group']/div[3]/div/div/div/input</value>
      <webElementGuid>5b1e58fe-4497-4530-9223-7ca0d0eb09de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div/form/div[3]/div/div/div/input</value>
      <webElementGuid>cd2cd9f0-990d-4636-96bb-9cae6fa19cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'score_group_weight' and @id = 'score_group_weight' and @placeholder = 'Bobot Kelompok Penilaian']</value>
      <webElementGuid>ca39f815-6901-4946-8144-584fa509a153</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
