<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_course_name</name>
   <tag></tag>
   <elementGuidId>7c58fde2-a0fb-4eb6-883f-29d35cc8c7e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='course_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#course_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>272ddda5-18b3-460b-825b-3524411344b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f433301c-3b68-4452-804c-693a67b17f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>course_name</value>
      <webElementGuid>e39c436e-e334-4654-973b-dd52907b3e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>course_name</value>
      <webElementGuid>958b4b0a-cdeb-4f2c-83c1-9916370a24d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ab05db18-8d06-44fd-8aee-21dd1947a99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi Nama Diklat</value>
      <webElementGuid>eca16d43-1ddf-43c6-b80c-b75dbd202035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>9e9a2b2f-c7e1-4c63-8f65-894df448afc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f1&quot;)/div[@class=&quot;card-body p-0&quot;]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;course_name&quot;]</value>
      <webElementGuid>15b1eac9-0e8f-4d25-8fdf-82fe2eb5f9ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='course_name']</value>
      <webElementGuid>b07e196f-14aa-476e-8fe3-96fdbdb73e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div[2]/input</value>
      <webElementGuid>2d0b6090-8c30-46fd-b662-79fa4b5917ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>473faa15-94ed-494c-9c6d-846257a61257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'course_name' and @id = 'course_name' and @placeholder = 'Isi Nama Diklat']</value>
      <webElementGuid>02fa6b73-e828-4468-995d-ef72be24732f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
