<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank Soal_tableSearch</name>
   <tag></tag>
   <elementGuidId>a88ac02d-859c-4660-91dd-01be30c155ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tableSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tableSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2594fc7f-0034-4566-b547-4f0d3fe7fb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>574b0347-eca7-4c42-82d5-347aa563b029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tableSearch</value>
      <webElementGuid>49cffe17-078a-4a8b-a43a-2b1a5a763cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>91937927-9c73-4a21-9c3f-596c99fd9704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pencarian...</value>
      <webElementGuid>3cd8dfc9-5d92-446c-807b-8f8ab0699b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableSearch&quot;)</value>
      <webElementGuid>e522555f-c145-4884-8975-60e886c97255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tableSearch']</value>
      <webElementGuid>b05c83e7-59c5-4ccf-8e37-4eb662354061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_search']/div/div/div/div/input</value>
      <webElementGuid>e49d0234-06b5-47b2-9e9e-2cf22ae9364e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a715130a-79a6-490d-91d6-b15dd79b1b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tableSearch' and @placeholder = 'Pencarian...']</value>
      <webElementGuid>f12d16d5-10ea-4e9b-b4ce-d2e01bd13f77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
