<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_File_literatur_file</name>
   <tag></tag>
   <elementGuidId>03fe5831-5c24-4333-8a97-e115945f7d33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#literatur_file</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='literatur_file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>947ff655-8d35-4d6f-976e-d02274a1ee08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control file</value>
      <webElementGuid>b53a93b7-88e3-45f3-98ee-4d90e9c9fb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>65232da4-0329-4d18-a64a-e5cc7ad5a66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>literatur_file</value>
      <webElementGuid>7fdad05b-8561-4ec6-88be-3dec52af6b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>literatur_file</value>
      <webElementGuid>f372a8fe-94dc-49cd-98d4-388577332f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;literatur_file&quot;)</value>
      <webElementGuid>82c39594-b6a1-4a01-a6d6-870a62632c7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='literatur_file']</value>
      <webElementGuid>24a31092-c008-4502-af08-2471557c2e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[11]/div/input[4]</value>
      <webElementGuid>430cf752-1af5-40d0-a474-43991690ec71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[4]</value>
      <webElementGuid>f120d677-4017-4bbf-8aee-8e255e02e42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'literatur_file' and @name = 'literatur_file']</value>
      <webElementGuid>86de6e00-e486-49f2-a05f-16234c3271b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
