<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_graduation_name</name>
   <tag></tag>
   <elementGuidId>c1db074a-8019-4341-b51b-d45eeabb878a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#graduation_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='graduation_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8238ba4-761f-4520-a5ab-7d81582caf12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f10c167-0013-431c-b507-c7036d19158c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>graduation_name</value>
      <webElementGuid>5ab1776e-1c39-4195-8f31-4c3f4af19c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>graduation_name</value>
      <webElementGuid>4149decb-827e-444a-b3b8-fbb7fc6339ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c5db6a6a-e377-4699-ab86-c641b56770a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Skala Penilaian</value>
      <webElementGuid>94031c5d-0b69-4ae7-afd1-ceaa21432cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;graduation_name&quot;)</value>
      <webElementGuid>c4848273-a9b0-475f-8704-ba5edb765997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='graduation_name']</value>
      <webElementGuid>c11bd16a-f5aa-41a2-9113-3696ce4f8689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div/input</value>
      <webElementGuid>e8998ab6-cdb9-4ea6-a9f3-596f267c5b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>ca206f24-c89f-472b-b737-86f4200b2bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'graduation_name' and @id = 'graduation_name' and @placeholder = 'Skala Penilaian']</value>
      <webElementGuid>11f7fe52-8942-4300-859f-5631433e16f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
