<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>13_isi objektif</name>
   <tag></tag>
   <elementGuidId>45d1cacb-d6a0-4c35-9550-3b251f0b9016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='curriculum_objective']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#curriculum_objective</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8b936502-f1f0-40f9-8a91-a3fe58fa353f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5e295543-7629-44de-9d3b-e657048b8f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d55e8c4b-85c0-436c-81dc-a77672d4cd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>curriculum_objective</value>
      <webElementGuid>e17f8807-177b-44c1-8fdb-0149226f37d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>curriculum_objective</value>
      <webElementGuid>bfd58553-593e-4e16-a384-f0276950247c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi objektif</value>
      <webElementGuid>50819ae6-ad5f-468e-afd9-994bb3ee27df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;curriculum_objective&quot;)</value>
      <webElementGuid>c578837a-9644-4b85-bef2-bba4ab438d97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='curriculum_objective']</value>
      <webElementGuid>282e0dbe-2821-46e8-a674-2d99a4265680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div[3]/textarea</value>
      <webElementGuid>c8c1dd03-1c03-471c-8267-14e127947d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>90941f84-b234-4d7f-895f-2a24143f18ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'curriculum_objective' and @id = 'curriculum_objective' and @placeholder = 'Isi objektif']</value>
      <webElementGuid>b8925f1d-fb96-461c-be47-1fea3fea4c33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
