<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kembali</name>
   <tag></tag>
   <elementGuidId>2fc2cff0-81c3-45c8-909c-7204e7ff0fac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger.position-absolute.waves-effect.waves-light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Kembali')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a938279e-7ab6-4312-9ff6-059f07b91470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://101.255.121.243:1180/master/module</value>
      <webElementGuid>7e9356d5-10e8-4141-9508-496891372e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger position-absolute waves-effect waves-light</value>
      <webElementGuid>2876a155-0b9f-4a0f-927f-856b2a258216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Kembali</value>
      <webElementGuid>3bc6f6eb-ccfc-4fc6-b275-5b4d06371b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;wrapper-box&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;container-fluid py-5 px-2&quot;]/div[@class=&quot;row mx-n1&quot;]/div[@class=&quot;col-md-12 position-relative&quot;]/a[@class=&quot;btn btn-danger position-absolute waves-effect waves-light&quot;]</value>
      <webElementGuid>3345a7d4-29f8-43f4-8771-25597f5feb9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kembali')]</value>
      <webElementGuid>45c1d75f-32bf-443c-996f-823aa8ce0552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Literatur'])[1]/following::a[1]</value>
      <webElementGuid>4a97bbf0-d75a-4ed1-a844-17fe62c19c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Topik'])[1]/following::a[2]</value>
      <webElementGuid>565ec0a8-6758-4ddc-985b-07b19e0ea152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MP-1000 - Ilmu Pertambangan'])[1]/preceding::a[1]</value>
      <webElementGuid>d5da2c06-df85-4394-bdc2-e34e520bf54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/preceding::a[1]</value>
      <webElementGuid>3bab1437-90b5-4a9c-968a-edeadf5b1e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kembali']/parent::*</value>
      <webElementGuid>3448ba27-9ed4-4900-acb1-e5bf6525675c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://101.255.121.243:1180/master/module'])[2]</value>
      <webElementGuid>c3355526-5c1e-4304-bcf0-5655af6a3c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>28453bf1-d4ac-4f0a-85e6-075e3a860e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://101.255.121.243:1180/master/module' and (text() = ' Kembali' or . = ' Kembali')]</value>
      <webElementGuid>f81b5c6d-2e2c-416c-80df-28a7c2e53c44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
