<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Jenis Diklat</name>
   <tag></tag>
   <elementGuidId>77f37560-41ee-4f65-b600-82a35d722418</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-opts_curiculums-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-opts_curiculums-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8c6b5223-1291-48a0-bd71-d2dca78d6555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>460ae777-0aa2-482e-8a3b-1ccfcb3806a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-opts_curiculums-container</value>
      <webElementGuid>621dfea2-745a-4330-afb2-6421b3f47664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d559f360-ea86-4ee7-abfe-e0660873f424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06a9e699-a842-4eb8-b2e0-77cd7ada46d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Jenis Diklat</value>
      <webElementGuid>8e34fb49-11f0-4767-857a-59a86863a20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-opts_curiculums-container&quot;)</value>
      <webElementGuid>dd0d0434-577b-4547-ba19-4f32d9b7e855</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-opts_curiculums-container']</value>
      <webElementGuid>fe24fe91-a7c1-4c94-9775-f723dc66f52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_search']/div/div/div[3]/span/span/span/span</value>
      <webElementGuid>2f496f5d-7fa8-4a2a-9ce9-5c7f1c841ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tahun Kurikulum'])[1]/following::span[6]</value>
      <webElementGuid>c597528d-5ff6-4ae2-8330-bfded05d080e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Soal'])[1]/following::span[11]</value>
      <webElementGuid>3236fc25-461f-4506-8756-5359ca2168ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/preceding::span[4]</value>
      <webElementGuid>389dc599-31a4-4b03-8b73-3a5f56b2bd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span/span</value>
      <webElementGuid>4157f734-2488-4ae4-8c7d-e5c67cd900bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-opts_curiculums-container' and (text() = 'Pilih Jenis Diklat' or . = 'Pilih Jenis Diklat')]</value>
      <webElementGuid>ab12c441-2f01-4f78-8b4d-fe875abb4357</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
