<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Fungsi_document_name</name>
   <tag></tag>
   <elementGuidId>06af7eeb-2835-4a67-892d-8d9030645328</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#document_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='document_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1f6c795f-59b7-43a8-bd4a-b10bda63bd6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9c7f80a0-5fa3-433e-af74-51fc695a80dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5aaede9f-414c-46e3-b30c-8864591e3d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>document_name[]</value>
      <webElementGuid>a5940bc7-7615-4bc8-a26c-3385faf5ee1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>document_name</value>
      <webElementGuid>93216297-88e7-4a7d-8d7b-b350361aad59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;document_name&quot;)</value>
      <webElementGuid>ec2fbdb9-4e22-4ec6-9b98-3ed5168e7ea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='document_name']</value>
      <webElementGuid>e6d09dd7-1a64-452f-bd8b-a40269711588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableWrapper']/tbody/tr/td/textarea</value>
      <webElementGuid>9f755e03-99ac-4e30-8fb5-6b7726c74d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c401ae55-778f-45df-8635-0f87e3d0ce3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'document_name[]' and @id = 'document_name']</value>
      <webElementGuid>f78e21fe-1e18-4754-a1b9-41267767861d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
