<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Satker_checkuser</name>
   <tag></tag>
   <elementGuidId>a625bb7d-9437-4aed-b714-05459b134335</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkuser_254']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkuser_254</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a9aba29-f45f-4ba2-921d-8f6b72318a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d759329e-c6c7-4da9-bcef-8de036178f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>toggleParticipantNum(this)</value>
      <webElementGuid>ad584c32-4dbf-40f6-b097-152c1b9349b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>654a22db-9bd1-4e49-a0c2-fe4dc8a0460b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkuser[]</value>
      <webElementGuid>ef6473e1-3a17-4ebe-b363-97bfb7fd325e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkuser_254</value>
      <webElementGuid>0aa4dcf9-47e0-4912-9d15-05ecbb56c057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>36b7dba8-9025-4d20-85a7-1675a62d53f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkuser_254&quot;)</value>
      <webElementGuid>8288bea5-ff7e-473c-86fc-eda8f2dec3fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkuser_254']</value>
      <webElementGuid>cb3248ae-d057-481b-ae4e-8588f5677952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_1']/tbody/tr/td/input</value>
      <webElementGuid>31e63a39-7e36-4a1d-bb62-2928b8441a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td/input</value>
      <webElementGuid>8dca701d-8b27-44da-8826-fe97d2add225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkuser[]' and @id = 'checkuser_254']</value>
      <webElementGuid>dbb2571d-47a5-4ed3-bf6a-eea64eeb71c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
