<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jam_schedule_start_time</name>
   <tag></tag>
   <elementGuidId>a0751678-6089-4d98-9023-a571cd887695</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='schedule_start_time']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#schedule_start_time</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60310fc6-ce25-4367-97ff-87573e21b73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3815ec44-66b4-40f7-95c3-6ec4e770b771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>schedule_start_time</value>
      <webElementGuid>3ac25494-762f-4dca-87ef-4c64eef6caf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>hh:mm</value>
      <webElementGuid>fb03b0ca-4aa4-49ee-9081-45bf05574301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>format_clock(this)</value>
      <webElementGuid>5c202a43-0625-40f5-aa59-89d762a63b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>db52bd7e-aeeb-46b0-8160-8966a7593193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>schedule_start_time</value>
      <webElementGuid>e7338b99-9894-4948-944c-aa96e589484c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control me-2 schedule_clock</value>
      <webElementGuid>5df3bc15-0254-470a-8583-38158769bbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schedule_start_time&quot;)</value>
      <webElementGuid>4f687383-8111-4ceb-86cc-20e71aab398c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='schedule_start_time']</value>
      <webElementGuid>6bebee2b-6248-4007-95c3-9b6494759aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_schedule_clock']/div/input</value>
      <webElementGuid>72827492-fd8e-4ca3-8468-fcc5fd199c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>661b0a10-c566-4d3c-b9e3-ece910a1d996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'schedule_start_time' and @placeholder = 'hh:mm' and @id = 'schedule_start_time']</value>
      <webElementGuid>ba05f867-3148-43e6-a6fd-20ec0ef10750</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
