<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sd_schedule_finish_time</name>
   <tag></tag>
   <elementGuidId>76e6229c-65af-4682-81f6-cd1def305b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='schedule_finish_time']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#schedule_finish_time</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b55f52fc-8f7f-4851-af53-a6c0abb23503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c45788fe-7825-4c4b-a6fd-5edf600ed673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>schedule_finish_time</value>
      <webElementGuid>e25cdfde-fd04-4e2d-8251-7807bf3d656b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>hh:mm</value>
      <webElementGuid>569558e8-1adb-41b7-96ae-c463de9f086b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>format_clock(this)</value>
      <webElementGuid>b7b49be7-b5bb-4d2d-9a34-d78b75425a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c8ec0b0a-b5ba-4aa1-be50-43d975cf80be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>schedule_finish_time</value>
      <webElementGuid>a5aff2f1-312c-4b77-b3b6-8d6a1bcf6e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ms-2 me-2 schedule_clock</value>
      <webElementGuid>ee23ba7c-bbf9-4344-95c9-6539d6c94050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schedule_finish_time&quot;)</value>
      <webElementGuid>1a11a600-0676-4b24-a3fe-cf28e0e3aa4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='schedule_finish_time']</value>
      <webElementGuid>7098ddf7-8695-491b-8d2d-da075347acac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_schedule_clock']/div/input[2]</value>
      <webElementGuid>23ace69b-a9f3-4117-9692-f77c7ca918f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>f9d15837-4cc1-416b-82c9-b031e0703b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'schedule_finish_time' and @placeholder = 'hh:mm' and @id = 'schedule_finish_time']</value>
      <webElementGuid>68b2df6e-8f0f-4fcd-8865-c0177b85c035</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
