<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Terjadwal dan Tak Terjadwal</name>
   <tag></tag>
   <elementGuidId>c7b9856f-8718-4e22-9902-9262e74a35b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-schedule_filter-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-schedule_filter-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>771246dc-8bda-45f1-b791-fb27345fe163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>a2943ec2-59ca-452c-acf9-71273dc4b53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-schedule_filter-container</value>
      <webElementGuid>8a394a38-05df-458d-9fe9-d9e66dd2502c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>dada8484-512b-46af-85be-3dab1a5a237f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f106bf8-41c6-4c21-9ba0-49e130038b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terjadwal dan Tak Terjadwal</value>
      <webElementGuid>10f82031-5786-4130-bdfa-8c5542ba6882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-schedule_filter-container&quot;)</value>
      <webElementGuid>2c630cef-ac03-4568-bf5e-13e0c8557ef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-schedule_filter-container']</value>
      <webElementGuid>dc3da95b-d733-4872-8fa8-0b55b817874b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_search']/div/div/div[2]/span/span/span/span</value>
      <webElementGuid>6327f7c8-f92d-43b8-820d-f6cf7ee1b5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Angkatan / Batch : IX/IV'])[1]/following::span[4]</value>
      <webElementGuid>31333c0a-3721-4dff-9a04-7b75498e96ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template Sertifikat'])[1]/following::span[4]</value>
      <webElementGuid>b4fbf25b-aff8-475f-bbbc-e6b648e9f7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalender'])[1]/preceding::span[4]</value>
      <webElementGuid>b37be6ad-de66-4dab-9a30-ba6c13133ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>962544b8-375f-4068-8a4c-804dd7a7d4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-schedule_filter-container' and (text() = 'Terjadwal dan Tak Terjadwal' or . = 'Terjadwal dan Tak Terjadwal')]</value>
      <webElementGuid>8dc1ad6d-c90d-47e8-b447-1035d12f3b66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
