<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Mulai_curriculum_date_start</name>
   <tag></tag>
   <elementGuidId>b35d322a-2f24-460c-b2d9-84051b4f9c33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#curriculum_date_start</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='curriculum_date_start']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f93e5f4e-8b0e-4597-b9ed-457a4db47c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4896fc2e-4685-4971-8f1b-c1691e9f62a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker</value>
      <webElementGuid>e9918f77-3b6a-42e3-96f7-64cea2f4dfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>curriculum_date_start</value>
      <webElementGuid>ab133a2c-7dd0-4366-8804-34cd82f33673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>curriculum_date_start</value>
      <webElementGuid>1c404426-8720-430f-954b-0e41a7be1062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>514ef15c-9bb9-491f-b4f0-78f0dc885f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>eec6f0b0-44f0-43da-97ef-0eaa51ddc29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;curriculum_date_start&quot;)</value>
      <webElementGuid>87957efb-b7ed-4de4-90b0-5a76954601c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='curriculum_date_start']</value>
      <webElementGuid>3a686809-d71a-45e7-bfa6-564a49c99c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div[2]/div/input</value>
      <webElementGuid>a06eda58-f1ba-4a9c-9e70-463d19613872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>12983442-e50e-4ace-8395-678789ecb06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'curriculum_date_start' and @id = 'curriculum_date_start' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>7004407a-ecc9-4a45-8736-bffc88281ee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
