<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_curriculum_name</name>
   <tag></tag>
   <elementGuidId>a75e5803-dee5-4585-8012-7c55bd365246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#curriculum_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='curriculum_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7be927b-dbe2-405c-987b-dc3820a0e6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c303e26-8e21-4248-9de6-c37240aa9d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>curriculum_name</value>
      <webElementGuid>957e7ccc-a2c5-4dbb-b29e-f96f148d3372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>curriculum_name</value>
      <webElementGuid>08c96630-871f-4b4b-ac82-48a0faecfe43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>391259b2-97b7-4aa5-956f-1313146424da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi Nama Jenis Diklat</value>
      <webElementGuid>45ffb3e5-7a9f-4e4e-ac46-3c3e9b428890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>fcbe44f4-be3e-4f5e-b80a-2962341487d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;curriculum_name&quot;)</value>
      <webElementGuid>8aad7ae5-fed9-4b82-ab9d-f7dc1c2b6d3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='curriculum_name']</value>
      <webElementGuid>7ad53725-c7c4-4c26-9bb3-e64bebf2fb13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div/input</value>
      <webElementGuid>bb9912c5-bce0-4e56-88fc-59e653aff062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>d776e132-c978-4d5f-9fa9-03db88b2dd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'curriculum_name' and @id = 'curriculum_name' and @placeholder = 'Isi Nama Jenis Diklat']</value>
      <webElementGuid>837f1334-4772-44f6-8ad2-026666f3f47c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
