<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank Soal_tableSearch</name>
   <tag></tag>
   <elementGuidId>f23084ca-5752-449c-ac9c-a3017a5df5fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tableSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tableSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66aca4f8-e17c-48b7-8e01-328ddea7417c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3302df33-7097-484b-89c8-1ee10557418e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tableSearch</value>
      <webElementGuid>cb4d771f-72f7-45ec-91c3-d49aeab6235d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b241b8c8-cee6-4a3b-8e64-d034b0d16176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pencarian...</value>
      <webElementGuid>96ba9433-b7c7-4393-acb5-164b1175f00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableSearch&quot;)</value>
      <webElementGuid>455e3b10-c393-4690-bb07-8a8c499f457a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tableSearch']</value>
      <webElementGuid>34582454-b559-4300-8509-268f2a3da4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_search']/div/div/div/div/input</value>
      <webElementGuid>af6acfd7-1d8b-4bf1-8521-c7fc3edb1b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>588649a5-9e99-4385-bce2-4144a4f2c63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tableSearch' and @placeholder = 'Pencarian...']</value>
      <webElementGuid>8f8e84f5-b78e-4e95-8d4d-c5b80c9cfcc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
