<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tujuan_curriculum_goal</name>
   <tag></tag>
   <elementGuidId>fd118f6c-8d56-4892-afbc-1235eaa8b781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#curriculum_goal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='curriculum_goal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>029b83f6-d099-49f2-97c3-adf0a122be70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9adffab9-c820-4438-8a5b-c01af0bf5582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9c622c6e-f415-4ff4-ba35-991957bffcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>curriculum_goal</value>
      <webElementGuid>4e0debc4-5e7c-4552-99fc-05c45946b033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>curriculum_goal</value>
      <webElementGuid>00ca2264-2165-43fa-bfef-34e89b04682c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi Tujuan</value>
      <webElementGuid>49db14c0-f800-46d7-a543-119838584ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;curriculum_goal&quot;)</value>
      <webElementGuid>d4baa035-2706-43d4-9d0f-3d5200601ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='curriculum_goal']</value>
      <webElementGuid>73f142d5-6520-4570-ae70-f275e7c2b8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div[4]/textarea</value>
      <webElementGuid>484c9b77-34a1-4c09-953d-cba38d6087c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/textarea</value>
      <webElementGuid>b90c1a2f-a9c7-47fd-968f-fab4ea086cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'curriculum_goal' and @id = 'curriculum_goal' and @placeholder = 'Isi Tujuan']</value>
      <webElementGuid>afb019a5-db1e-4627-8b41-e25a7cab3f64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
