<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>upload file</name>
   <tag></tag>
   <elementGuidId>0090bd3c-9fb1-4411-b0ae-6e9e26e1032c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#photo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='photo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb0f3086-3676-450b-afc3-65b0bec72c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control file</value>
      <webElementGuid>db208a91-65b8-47b9-8095-19b42050fa3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>bb9fb7a6-3b2d-4460-8c90-6cdfc93942aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>photo</value>
      <webElementGuid>d5bbac1c-b0a8-43e9-ac9a-dad3a292e379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>photo</value>
      <webElementGuid>d86fe2c4-8b41-408c-a2e9-3c9b1e83411c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;photo&quot;)</value>
      <webElementGuid>08fb6c6c-f806-4114-b69a-7729e2bf5db2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='photo']</value>
      <webElementGuid>fc15981b-c5c0-4395-a3b7-fcce02b0395f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div[5]/div/input[4]</value>
      <webElementGuid>c24c9224-714b-40aa-b740-8dfb9cb881c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[4]</value>
      <webElementGuid>e20bbd95-b5c4-4dbf-a9bc-cd6b8dacc603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'photo' and @name = 'photo']</value>
      <webElementGuid>f36ff72c-c48b-4d1f-bc15-4fed4ffb1001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
