<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Atur Jadwal</name>
   <tag></tag>
   <elementGuidId>7e583fc7-9edb-4d78-a22d-8af3b9936a46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='set_schedule(this);']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.no-button.no-shadow.btn-sm.delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0c40162-efd2-4903-be84-05fd53268b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn no-button no-shadow btn-sm delete</value>
      <webElementGuid>51c42127-3878-4c6a-ad26-9959c44e643c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>set_schedule(this);</value>
      <webElementGuid>64bf75c6-77e9-46d2-964e-49dd1cac7263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ccl-id</name>
      <type>Main</type>
      <value>87</value>
      <webElementGuid>fd2ceb51-0041-4336-b715-91d5c177956d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cco-id</name>
      <type>Main</type>
      <value>102</value>
      <webElementGuid>217e99b7-8f61-4e13-92c1-9f95ea2dfbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mod-data</name>
      <type>Main</type>
      <value>MP-016 - Eksekusi </value>
      <webElementGuid>c46974f9-e322-4e22-ac46-442d94c90e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>87</value>
      <webElementGuid>8568058d-ab6e-4ff5-aade-3b9ad7891ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Atur Jadwal</value>
      <webElementGuid>fd0aece5-8f6c-4039-a989-e9b7401e4e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[9]/button[@class=&quot;btn no-button no-shadow btn-sm delete&quot;]</value>
      <webElementGuid>1d4e21f3-fdee-4fbb-9ebd-559086a7c47e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='set_schedule(this);']</value>
      <webElementGuid>f5eb2297-144c-4990-ac01-2eb2e7821387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[9]/button</value>
      <webElementGuid>96a89cd7-926f-4a6a-bfb6-54bd4027b1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Terjadwal'])[3]/following::button[1]</value>
      <webElementGuid>e9f4a546-af18-42b2-a37f-3b1e274457f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Terjadwal'])[2]/following::button[1]</value>
      <webElementGuid>00b413c5-aa78-43a4-b420-db3d4371593a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries'])[1]/preceding::button[1]</value>
      <webElementGuid>db65edf9-788a-44f8-8a66-d4abb0e192e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Atur Jadwal']/parent::*</value>
      <webElementGuid>c9e6d6f0-f8e1-462d-8ad4-cfffcf208ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/button</value>
      <webElementGuid>2f912a89-0344-4d76-b8a1-6053a38dabb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Atur Jadwal' or . = ' Atur Jadwal')]</value>
      <webElementGuid>63d46ffa-071d-4ce6-b5f5-f76ff5f11dea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
