<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ubah</name>
   <tag></tag>
   <elementGuidId>22452709-8af7-4d04-a1a3-a020713ca6a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='handleEdit();']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-danger.waves-effect.waves-light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a74741aa-e078-4e93-b03e-74df18f08b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-danger waves-effect waves-light</value>
      <webElementGuid>47746ecf-9284-479b-9674-93fc770e4ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>handleEdit();</value>
      <webElementGuid>22372a83-4334-44ac-a57e-614343a5dddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ubah</value>
      <webElementGuid>43e40b8e-0788-4a86-b887-2f310593ae7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view-wrapper&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-md-4&quot;]/button[@class=&quot;btn btn-sm btn-danger waves-effect waves-light&quot;]</value>
      <webElementGuid>0e26ee96-07ee-440a-a677-7d85b3caf945</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='handleEdit();']</value>
      <webElementGuid>3648f30c-d0a9-44dc-b9e0-c63fa94c4395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view-wrapper']/div/div[2]/div[2]/button</value>
      <webElementGuid>97d70039-df5e-41cc-a394-a7f69a8aecf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=': -'])[1]/following::button[1]</value>
      <webElementGuid>d0154c2c-a996-41d2-b32b-a0800893f6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Template'])[1]/following::button[1]</value>
      <webElementGuid>05c0e310-ffb3-4b61-84ab-f1757a911555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Template'])[2]/preceding::button[1]</value>
      <webElementGuid>77e919eb-fe4a-4d8b-9460-96247e30da3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--- Search ---'])[1]/preceding::button[1]</value>
      <webElementGuid>9fd6b419-18ce-4ec2-85d0-8e6ebecd51f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah']/parent::*</value>
      <webElementGuid>dad65715-40e3-49ca-a377-fa8a83da060e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>dc5871ce-73c5-47e1-8328-284262af2824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Ubah' or . = ' Ubah')]</value>
      <webElementGuid>3d7de767-3526-40a9-a51e-63ba3a9f9958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
