<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kapasitas Ruang Kelas_room_capacity</name>
   <tag></tag>
   <elementGuidId>a3fc0869-2ee3-4e99-ac74-4f983d07d2ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#room_capacity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='room_capacity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a51389cc-94d7-48ab-a5db-3cb1497e9ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1fb11d3e-8470-45c5-bd7c-86f522a96486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control room_capacity</value>
      <webElementGuid>3cb841cb-8e52-472a-ac92-6d5cff209fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>room_capacity</value>
      <webElementGuid>fcf5e070-3c0b-42c5-9093-daec6ee9af5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>room_capacity</value>
      <webElementGuid>de4bc13c-dbf5-4a30-b69c-38583407a7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5d76e5d3-89c2-4852-8d7d-793259a1bfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>543e59b8-63d1-417e-89a8-823f39eb7505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;room_capacity&quot;)</value>
      <webElementGuid>506f8e12-f9cb-439d-82b9-28603bbe857c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='room_capacity']</value>
      <webElementGuid>6436bdaa-2581-4416-8fc4-2cd708fdbed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/div[5]/div/input</value>
      <webElementGuid>d3521010-c0c7-4e31-b870-1bde9e1fc56c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>e7ca40f6-ed0b-44ad-8225-54df3eceaed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'room_capacity' and @id = 'room_capacity' and @placeholder = '0']</value>
      <webElementGuid>768f10b1-0063-491a-a812-f3a8a96212f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
