<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Import_tableSearch</name>
   <tag></tag>
   <elementGuidId>5584a573-8157-4f7f-95c0-368246aa5c02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tableSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tableSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4188477-4898-405e-a140-0a78e230d250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e29770c9-527f-4178-96d6-f4c71dcd696d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tableSearch</value>
      <webElementGuid>c87e9335-1002-4b4a-9bb2-3c1c5e23cec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>94a6d91f-e851-41dc-82a2-d8916ca4ff82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pencarian...</value>
      <webElementGuid>e3eaffef-f281-4545-88f6-e42143cbbb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableSearch&quot;)</value>
      <webElementGuid>7bc02e3f-f0d2-41b8-98ea-647264cb7057</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tableSearch']</value>
      <webElementGuid>d1a42166-70a4-494d-ae47-970da1dbce03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_search']/div/div/div/div/input</value>
      <webElementGuid>d9c91ba3-7758-421c-9419-a86e40c6fca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>25635dd3-28b2-4d0a-9a3b-55cd9bfd322a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tableSearch' and @placeholder = 'Pencarian...']</value>
      <webElementGuid>0b50673d-5806-417d-97b9-43ca4199156b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
