<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_user_dob</name>
   <tag></tag>
   <elementGuidId>943de66e-7b61-4b88-9bfe-c3111b9ca4e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_dob']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user_dob</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d3c1583-b025-42d6-aae3-fabb61ebd093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99d8d97a-f07b-4c9b-8e57-4f6e0c910b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker</value>
      <webElementGuid>0f57e270-361d-4135-a7eb-cbacb3833ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_dob</value>
      <webElementGuid>af712c45-c115-4ef5-a5b3-f1972a3158d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_dob</value>
      <webElementGuid>4ebc347d-4634-4fda-8c1f-81eb10c6374d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>c024ce0b-bb5b-4582-8308-e1e0fa602f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ce2f5875-c349-48af-a017-3210130541c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_dob&quot;)</value>
      <webElementGuid>6c8084a6-b86d-4920-abc8-2d6e29c808c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_dob']</value>
      <webElementGuid>a28b9fd5-fd47-43eb-ba57-8dfd21e554ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_user_data']/fieldset/div/div/div/div[6]/div[2]/input</value>
      <webElementGuid>7cd6a232-a3e9-433f-8fe0-59646ed7bc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>6e206c5b-8f0c-4536-9b5f-19746e6f7bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'user_dob' and @name = 'user_dob' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>e2182368-20ee-473f-a7dd-ae7bc592a391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
