<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Kejaksaan Tinggi Jawa Barat</name>
   <tag></tag>
   <elementGuidId>abaebf32-a81b-45e4-a6b7-5a0ce5b27c1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-riu_id-result-vk4d-8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-riu_id-result-vk4d-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>00ae8b06-3417-46ae-9d1c-c1cac3a7c4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>4b71fd72-66fc-4650-baad-c57907ed36c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-riu_id-result-vk4d-8</value>
      <webElementGuid>7d4191d5-6fcf-488f-baed-0ffdcd6a0176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c15a70d4-d7ff-4217-9ba1-fc17e8bfa45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>51559864-cedb-4858-9dc2-cc0130fd965f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-riu_id-result-vk4d-8</value>
      <webElementGuid>161477cb-f9d8-4f11-bba9-95323c2d0c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kejaksaan Tinggi Jawa Barat</value>
      <webElementGuid>1b1d04b0-616e-4089-8645-dc3ea594c061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-riu_id-result-vk4d-8&quot;)</value>
      <webElementGuid>69480a95-ba7b-43ab-b320-a213d12467ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2879090a-f11a-4025-8eed-fbacde253089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>d5ec5d64-ec59-439b-adc2-e99830b69ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-riu_id-result-vk4d-8</value>
      <webElementGuid>e3c9d095-9e95-4e06-9e25-63d5346ce312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>48067ac7-cfad-4db2-8a79-c3db983c126a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1672cc7-78c2-4713-bc53-3a14864031bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-riu_id-result-vk4d-8</value>
      <webElementGuid>14a13bb2-2189-4136-b9dc-91183b35e8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kejaksaan Tinggi Jawa Barat</value>
      <webElementGuid>a9266101-a9da-4d8a-822b-8acf43ad7e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-riu_id-result-vk4d-8&quot;)</value>
      <webElementGuid>47484f11-dc6b-4b20-a9dc-311bfa5e9d1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-riu_id-result-vk4d-8']</value>
      <webElementGuid>566d4a93-a42c-4781-b3aa-e051140b4ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-riu_id-results']/li</value>
      <webElementGuid>2306fde1-3c38-48e9-9663-92cc024ece6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusat Notifikasi'])[1]/following::li[1]</value>
      <webElementGuid>abe57851-963d-4b93-86b1-07cb8a552fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[8]/following::li[1]</value>
      <webElementGuid>0967725a-3f7d-44b4-814a-2ae62fcaefe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kejaksaan Tinggi Jawa Tengah'])[2]/preceding::li[1]</value>
      <webElementGuid>49cc3f81-c83b-4e40-974b-676993814961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kejaksaan Tinggi Jawa Timur'])[2]/preceding::li[2]</value>
      <webElementGuid>871d99c7-0622-4ec5-83ee-002867367173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li</value>
      <webElementGuid>09d2f0ad-a506-4f11-b67b-32d19c03f996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-riu_id-result-vk4d-8' and (text() = 'Kejaksaan Tinggi Jawa Barat' or . = 'Kejaksaan Tinggi Jawa Barat')]</value>
      <webElementGuid>49e82839-7230-4cd7-aa3f-5671f5ba2a11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
