<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_WIBWITAWIT</name>
   <tag></tag>
   <elementGuidId>e8d4d0c8-ba8d-4ec9-804f-80918f746e74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='timezone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#timezone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6f7d0380-69eb-436d-a056-0653e800ed49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>timezone</value>
      <webElementGuid>4d2fdf7d-2953-490b-bc53-449293ffba16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timezone</value>
      <webElementGuid>c72ce09e-21e0-4a9d-9219-f940127b153a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select</value>
      <webElementGuid>b7676c5c-477b-41c7-a63e-352fd9c24cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
WIB
WITA
WIT
</value>
      <webElementGuid>389946f5-a806-4fc3-946b-5b0d51e3439e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timezone&quot;)</value>
      <webElementGuid>2ecbf665-38f2-49a2-9e16-0aff6cf440c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='timezone']</value>
      <webElementGuid>fe0f7c99-06f5-49f0-9ff7-d38f58ba5279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_user_data']/fieldset/div/div/div/div[14]/div/select</value>
      <webElementGuid>10f4ca74-a0c2-4922-afac-24a8e2f28c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zona Waktu (WIB/WITA/WIT)'])[1]/following::select[1]</value>
      <webElementGuid>f000b7d8-0357-4602-a5bd-619a0dd3389a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Angkatan'])[1]/following::select[1]</value>
      <webElementGuid>67433a14-b2eb-4937-b87e-b09d7c2c10bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Rekening'])[1]/preceding::select[1]</value>
      <webElementGuid>2d5ae539-bd32-4091-8e0e-0a5862c1f1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload File Buku Rekening'])[1]/preceding::select[1]</value>
      <webElementGuid>c1a7a36c-f28e-4d1f-86b0-226b3820943b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/select</value>
      <webElementGuid>833f5745-22d0-4150-b4ca-7df47c4f2191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'timezone' and @id = 'timezone' and (text() = '
WIB
WITA
WIT
' or . = '
WIB
WITA
WIT
')]</value>
      <webElementGuid>c1fb430c-e59d-4b0f-9a63-eb49ea1504f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
