<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pencarian</name>
   <tag></tag>
   <elementGuidId>0d4fb040-fc3e-47f2-8cdd-5ee838f64186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-edu_id-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-edu_id-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b029d33d-aa69-46f0-b1d8-b4a1f7c7e547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>256c2f98-babc-49b6-90b5-e93920ac0dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-edu_id-container</value>
      <webElementGuid>2d6b4073-3e6d-4658-9426-8093f64389d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>adf8665b-fa7e-4964-bb2b-2f22968df320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3925f7d1-3410-4a00-a369-fe46b84b2545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pencarian...</value>
      <webElementGuid>b028d6d1-7a88-4402-b770-47d837330f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-edu_id-container&quot;)</value>
      <webElementGuid>6f459e47-4167-4512-904e-ca3df883808b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-edu_id-container']</value>
      <webElementGuid>60f3e4d6-dc34-4298-bb72-efb6d5bfbcad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_user_data']/fieldset/div/div/div/div[11]/div/span/span/span/span</value>
      <webElementGuid>0252d9d0-9917-4dce-a0fb-d94a655a7732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[8]/following::span[4]</value>
      <webElementGuid>dade0aae-3d0b-43de-962d-d827b4f9234f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TMT'])[1]/preceding::span[4]</value>
      <webElementGuid>ed4fddfd-f717-4d2b-b216-b9bfe274a88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>9fcf3104-c171-4efb-b9d6-3ddd82fa7e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-edu_id-container' and (text() = 'Pencarian...' or . = 'Pencarian...')]</value>
      <webElementGuid>5616216c-0fa7-4a89-b96b-613f020efa9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
