<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_go_to_prev_page</name>
   <tag></tag>
   <elementGuidId>503b9a68-5745-403c-8cc3-ddfc922b7cde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='go_to_prev_page']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#go_to_prev_page</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b067e8c9-7db1-4464-9d23-591060a76dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5f169e59-9e3f-4088-a3cd-7311a8777d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e8dd2f3f-651a-4199-83be-e7796767f49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>go_to_prev_page</value>
      <webElementGuid>06b23749-5f68-4c80-ab08-a9ba38facb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go_to_prev_page</value>
      <webElementGuid>ea83528c-1153-4431-9fe9-67772438024b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go_to_prev_page&quot;)</value>
      <webElementGuid>a3d06f29-3a5c-4358-a2f0-f330ab022438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='go_to_prev_page']</value>
      <webElementGuid>acb99b38-26b1-4ede-a17a-c94900a88729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/fieldset/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>8de3ed1a-5131-4559-8750-b5d823e4a29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>16f9fdff-9b89-4dc0-8be4-9164638e331e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'go_to_prev_page' and @id = 'go_to_prev_page']</value>
      <webElementGuid>a24742cc-e1e5-4660-90cc-71a5afbc38b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
