<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_assignment_name</name>
   <tag></tag>
   <elementGuidId>e6e3f0e5-4ee5-4aa4-84b6-23ca9709bb8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='assignment_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#assignment_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>603512bf-199e-4d1e-8748-b0226f9c93c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7db6aad0-328e-4224-bf54-03aafc8f9b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2c92548b-d213-430c-b1c2-c9ad3e033330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assignment_name</value>
      <webElementGuid>38390f7a-e12b-4dae-b455-023f38efc11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assignment_name</value>
      <webElementGuid>3f3de4db-9ad8-44d4-ac81-24b2730a54ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00002  -  PPPJ GELOMBANG II TAHUN 2016 - Kelas 2 - Agama dan Budi Pekerti</value>
      <webElementGuid>289d0996-28bc-4c81-ad5b-9408f11e2ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi Judul</value>
      <webElementGuid>792f8c55-2e50-41e9-96b3-c5144d73cd0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>f6d312a2-5289-4cf6-9c2f-f825dd984376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignment_name&quot;)</value>
      <webElementGuid>08bc7748-e059-44de-a946-ade6af8f483d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='assignment_name']</value>
      <webElementGuid>b9d8c1a4-d26c-44ee-af60-e9e316643a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[2]/input</value>
      <webElementGuid>719834d7-f374-45b7-b28a-95173b6698fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>3e64f338-0584-4e2a-aa1e-a60bf11b821d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'assignment_name' and @id = 'assignment_name' and @placeholder = 'Isi Judul']</value>
      <webElementGuid>65228f26-7d6e-4f6c-a792-a62634c1b7e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
