<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih JenisUjianTugasQuiz</name>
   <tag></tag>
   <elementGuidId>1b81b38a-c836-4b8b-b8d1-59a59cae13d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='assignment_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#assignment_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9f2f7077-833f-49b3-bc9c-7792189c3b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assignment_type</value>
      <webElementGuid>e931216a-1a50-4390-a618-1b35ee2a103d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assignment_type</value>
      <webElementGuid>231fd414-5b95-4cfc-8acb-11e24f663443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fieldinput select2 form-select</value>
      <webElementGuid>3138828d-4afa-49b2-9b92-44bd5c0afccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Pilih Jenis
Ujian
Tugas
Quiz
</value>
      <webElementGuid>136dce3d-cd3c-46e0-9561-a2f8ed580ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignment_type&quot;)</value>
      <webElementGuid>c51b33fd-293e-4805-95cd-b515d3f7ffeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='assignment_type']</value>
      <webElementGuid>f1d57614-d431-4a4a-8a6e-ec887cfa42d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div/select</value>
      <webElementGuid>594f1995-9ec6-4b20-9a28-ffec50ccf0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[1]/following::select[1]</value>
      <webElementGuid>2b570bd1-e647-47b3-9b25-484ce50740ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[2]/preceding::select[1]</value>
      <webElementGuid>6a99b03b-a2bd-43f8-8f8f-56b37fb36dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f3424743-1298-4c55-80be-f227cca9da54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'assignment_type' and @id = 'assignment_type' and (text() = '
Pilih Jenis
Ujian
Tugas
Quiz
' or . = '
Pilih Jenis
Ujian
Tugas
Quiz
')]</value>
      <webElementGuid>6829dec8-1940-4952-ae67-d4ade4278e52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
