<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih MetodeOnlineOffline</name>
   <tag></tag>
   <elementGuidId>6b3ac733-87c5-44db-aa20-dea88fe345ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='is_online']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#is_online</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9773a205-d45a-4e40-9dfd-ab7c8dcebdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_online</value>
      <webElementGuid>1255d014-0b47-4aeb-ab8e-d2bd231c6520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_online</value>
      <webElementGuid>b2acc674-fc3d-4e39-9a5f-85afff0bbd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fieldinput select2 form-select</value>
      <webElementGuid>945bfd1c-2178-40ec-b832-79b8d02432cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Pilih Metode
Online
Offline
</value>
      <webElementGuid>a034f771-421d-4a28-b699-226e6d00d771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is_online&quot;)</value>
      <webElementGuid>1ec4d2fb-1a39-4174-bc97-bf371086c124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='is_online']</value>
      <webElementGuid>b9a8bf2a-6901-41f9-ae45-1b8797d90733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[6]/div/select</value>
      <webElementGuid>8fce0e33-7d1b-4e47-ab41-815b5af4b19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[8]/following::select[1]</value>
      <webElementGuid>ae143e2c-6de4-4ad5-ab8e-490fde17f07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[9]/preceding::select[1]</value>
      <webElementGuid>ffe39295-c4a2-4ec9-8c22-6794fe4372ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>c2bb99a7-eee1-4ac7-9eba-7796f09585a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'is_online' and @id = 'is_online' and (text() = '
Pilih Metode
Online
Offline
' or . = '
Pilih Metode
Online
Offline
')]</value>
      <webElementGuid>99f73160-fdea-41bc-9560-15950508fe4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
