<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_------- Diklat -------</name>
   <tag></tag>
   <elementGuidId>b808e86f-bc24-45e2-bffc-ab3d516f6cd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-training-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-training-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd7c941c-d565-49db-aeaf-6a3d50373cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>591bfbc8-0ab0-4836-9abe-b3162ddbc18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-training-container</value>
      <webElementGuid>0bb007d0-4b65-4c10-87a1-afcdac179499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>de31adc6-b341-4dbd-b9b8-8ef1bbf2a2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3c206d95-c013-44fd-ade8-e20abf89cf60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>------- Diklat -------</value>
      <webElementGuid>1edb9b88-3ff8-4938-9334-176ac92516c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-training-container&quot;)</value>
      <webElementGuid>214c968a-9e85-4203-bfb6-55576b49d57c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-training-container']</value>
      <webElementGuid>460978c7-dfcd-4989-9c92-d0e9e2867f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='text-editor']/div/div/div/table/tbody/tr/td[2]/span/span/span/span</value>
      <webElementGuid>eb7fa296-b7d2-40f3-b69e-72c8ae7a9bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[1]/following::span[4]</value>
      <webElementGuid>485d4eab-17c4-4f99-839e-305322f8d804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>876398d7-2c21-4f7b-96e1-44eacdcc2db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-training-container' and (text() = '------- Diklat -------' or . = '------- Diklat -------')]</value>
      <webElementGuid>79108c58-b95d-4345-957d-565d3677b9df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
