<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kembali_1_2</name>
   <tag></tag>
   <elementGuidId>73b00c75-271b-4fd8-84b4-804ce02230d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Kembali')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger.btn-sm.mb-0.waves-effect.waves-light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>913610d2-35c8-4fab-89ac-2143b185b79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://101.255.121.243:1180/classroom/myclassroom/learning-module/materials/view/32</value>
      <webElementGuid>49dc3bf4-7e6b-49d7-b37e-889e1a13a7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm mb-0 waves-effect waves-light</value>
      <webElementGuid>baab964c-a901-425f-a906-0714d613dc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Kembali</value>
      <webElementGuid>88d3aae6-b64f-4446-81af-fa6621a4269c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;wrapper-box&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;container-fluid py-5 px-2&quot;]/div[@class=&quot;panel-header-page d-flex align-items-center px-3&quot;]/div[@class=&quot;col-md-4&quot;]/a[@class=&quot;btn btn-danger btn-sm mb-0 waves-effect waves-light&quot;]</value>
      <webElementGuid>f3c6a3a0-2bd6-4c9c-8949-72162c9b41cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kembali')]</value>
      <webElementGuid>a912bf6c-da64-417b-99ad-3e17b456c971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Soal'])[1]/following::a[1]</value>
      <webElementGuid>c1055ab9-8f8e-437d-972d-b01bb74b719c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template Sertifikat/Ijazah'])[1]/following::a[2]</value>
      <webElementGuid>bc9090aa-e531-4841-91cf-1177e569d712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modul Ajar'])[2]/preceding::a[1]</value>
      <webElementGuid>1454df14-b50f-4a84-bd9c-7b15cd2143f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama berkas'])[1]/preceding::a[1]</value>
      <webElementGuid>1a4fc687-cb1a-40f9-b260-e88c815b0a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kembali']/parent::*</value>
      <webElementGuid>0a7d77f6-7aed-430e-a6e3-f954ad596150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://101.255.121.243:1180/classroom/myclassroom/learning-module/materials/view/32']</value>
      <webElementGuid>e259f1b1-cf92-4e13-afbd-308c8c31570b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>cfdd4647-124c-470d-9aed-c9b6f493613f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://101.255.121.243:1180/classroom/myclassroom/learning-module/materials/view/32' and (text() = ' Kembali' or . = ' Kembali')]</value>
      <webElementGuid>a28708bc-0a82-4aea-9def-20311ba94bb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
