<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hukum_Pidana.pdf</name>
   <tag></tag>
   <elementGuidId>c525a893-3ad5-4dd5-9b74-13c6157a8d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Hukum_Pidana.pdf')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ms-3 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c7530e7-f38c-4246-adf9-440eeeaa03cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://103.253.107.18:24400/uploads/library/Hukum_Pidana.pdf</value>
      <webElementGuid>bbbfffb5-6ac7-4e4b-ba04-95c089327004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>ec9c36f3-ba87-4ba5-8b20-56efa6fd3b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hukum_Pidana.pdf</value>
      <webElementGuid>fcefadcd-a145-4812-8cac-af6d6bf115f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;wrapper-box&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;container-fluid pt-5 px-0&quot;]/div[@class=&quot;elib-main-content-container&quot;]/div[@class=&quot;elib-detail-item&quot;]/div[@class=&quot;bg-white w-100 d-flex flex-column shadow rounded justify-content-between ms-4 p-3 br-4&quot;]/div[1]/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;ms-3&quot;]/a[1]</value>
      <webElementGuid>01150aff-41b1-47a4-b41a-84cbbf569fcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hukum_Pidana.pdf')]</value>
      <webElementGuid>56d332f2-774c-42cc-ac1a-686d4db96c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::a[1]</value>
      <webElementGuid>f9035159-e7ce-4714-b095-fb9960f33c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun Terbit'])[1]/following::a[1]</value>
      <webElementGuid>df13229b-fc2e-4c80-9707-c6fc74d47760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusat Notifikasi'])[1]/preceding::a[1]</value>
      <webElementGuid>89062f2a-872b-4a61-a142-3eede00e024c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hukum_Pidana.pdf']/parent::*</value>
      <webElementGuid>e95a3818-ec45-440c-b289-cd00fe28cd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://103.253.107.18:24400/uploads/library/Hukum_Pidana.pdf']</value>
      <webElementGuid>658c969d-4024-4646-9b3a-736d896d480d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>6ccc21fb-b05b-44d4-b663-2fabd821218a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://103.253.107.18:24400/uploads/library/Hukum_Pidana.pdf' and (text() = 'Hukum_Pidana.pdf' or . = 'Hukum_Pidana.pdf')]</value>
      <webElementGuid>5f767d91-9829-4313-9794-ef342167c849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
