<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kepemimpinan_Leadership.pdf</name>
   <tag></tag>
   <elementGuidId>8f6a13b9-6ef2-46c1-b0ee-88ab088f30b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ms-3 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Kepemimpinan_Leadership.pdf')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec2f05c7-e58a-457d-ad5f-dce273f97176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://101.255.121.243:1180/uploads/library/Kepemimpinan_Leadership.pdf</value>
      <webElementGuid>d9b806f3-98ac-4ff4-8366-4480132449d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>ace4b6f1-50d8-4dd7-a2ab-6476cd027b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kepemimpinan_Leadership.pdf</value>
      <webElementGuid>2e727dd8-06a9-4ee1-a406-1f7a1aa1d153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;wrapper-box&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;container-fluid pt-5 px-0&quot;]/div[@class=&quot;elib-main-content-container&quot;]/div[@class=&quot;elib-detail-item&quot;]/div[@class=&quot;bg-white w-100 d-flex flex-column shadow rounded justify-content-between ms-4 p-3 br-4&quot;]/div[1]/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;ms-3&quot;]/a[1]</value>
      <webElementGuid>66412142-cddf-4979-a64c-8cb0a9b527ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kepemimpinan_Leadership.pdf')]</value>
      <webElementGuid>dae7bd1a-9f03-4354-8963-3e6c8658d549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::a[1]</value>
      <webElementGuid>5bc920ab-f64d-4077-96b5-8e5087082ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun Terbit'])[1]/following::a[1]</value>
      <webElementGuid>a5e4c2ad-2723-4c88-bb52-da15c02fcd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusat Notifikasi'])[1]/preceding::a[1]</value>
      <webElementGuid>65f8a83a-4e51-4147-b904-9b35201e14e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kepemimpinan_Leadership.pdf']/parent::*</value>
      <webElementGuid>d9c7c620-d2d9-42b9-b6d3-68c007c2ef59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://101.255.121.243:1180/uploads/library/Kepemimpinan_Leadership.pdf']</value>
      <webElementGuid>0a729474-da03-4511-bb96-3eed1c5dba0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>1e4929c2-ea7f-43ca-bc4f-430d625d25a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://101.255.121.243:1180/uploads/library/Kepemimpinan_Leadership.pdf' and (text() = 'Kepemimpinan_Leadership.pdf' or . = 'Kepemimpinan_Leadership.pdf')]</value>
      <webElementGuid>98420c97-cc2b-403d-9a31-1648bc0eaa55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
