<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_METODOLOGI_PENELITIAN_HUKUM_PROGRESSIF.pdf</name>
   <tag></tag>
   <elementGuidId>bfe77a78-8bc2-4bfe-86de-0fbbbe1c9fb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'METODOLOGI_PENELITIAN_HUKUM_PROGRESSIF.pdf')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ms-3 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed42c6b7-e518-472f-b0a9-285be28533bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://103.253.107.18:24400/uploads/library/METODOLOGI_PENELITIAN_HUKUM_PROGRESSIF.pdf</value>
      <webElementGuid>5fccb31c-8191-40f6-9284-003d6f29c1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>77a0fbdf-89ac-40ba-856d-2014fe3fe1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>METODOLOGI_PENELITIAN_HUKUM_PROGRESSIF.pdf</value>
      <webElementGuid>1a8726c7-4332-41fd-b654-d0ef1eb270b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;wrapper-box&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;container-fluid pt-5 px-0&quot;]/div[@class=&quot;elib-main-content-container&quot;]/div[@class=&quot;elib-detail-item&quot;]/div[@class=&quot;bg-white w-100 d-flex flex-column shadow rounded justify-content-between ms-4 p-3 br-4&quot;]/div[1]/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;ms-3&quot;]/a[1]</value>
      <webElementGuid>72e3f380-4501-49b3-82ab-d32a5e23e001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'METODOLOGI_PENELITIAN_HUKUM_PROGRESSIF.pdf')]</value>
      <webElementGuid>94836032-d69f-4a59-a1ad-19e5b2be522a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::a[1]</value>
      <webElementGuid>8f71546f-5a9d-4090-ad88-556d8e24920e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun Terbit'])[1]/following::a[1]</value>
      <webElementGuid>8fc18111-4b8f-4fcf-95da-b3538e12c540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusat Notifikasi'])[1]/preceding::a[1]</value>
      <webElementGuid>34e0b23a-d8a5-4353-b0f2-5c71b519cd86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='METODOLOGI_PENELITIAN_HUKUM_PROGRESSIF.pdf']/parent::*</value>
      <webElementGuid>0872241c-0532-45a7-8512-c2b64d07d164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://103.253.107.18:24400/uploads/library/METODOLOGI_PENELITIAN_HUKUM_PROGRESSIF.pdf']</value>
      <webElementGuid>c4f62ebf-a00b-47d3-b946-09bd8c7d9081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>59f302e2-ca99-4f66-b830-37fd86bf0429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://103.253.107.18:24400/uploads/library/METODOLOGI_PENELITIAN_HUKUM_PROGRESSIF.pdf' and (text() = 'METODOLOGI_PENELITIAN_HUKUM_PROGRESSIF.pdf' or . = 'METODOLOGI_PENELITIAN_HUKUM_PROGRESSIF.pdf')]</value>
      <webElementGuid>290a702f-2c29-4bed-8e89-9917e17c662f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
