<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Quiz_btn btn-light btn-sm waves-effect wa_624323</name>
   <tag></tag>
   <elementGuidId>03a84dda-5ebc-47d6-b99a-7428a313794e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='view_mapel']/div/div/div/table/tbody/tr[2]/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>31d1938d-8b8c-4619-9f9e-c98d6f950080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light btn-sm waves-effect waves-light</value>
      <webElementGuid>79c3081a-3c4f-4d91-a31f-36a064982421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://101.255.121.243:1180/classroom/scores/lesson/33/50</value>
      <webElementGuid>637e9004-4387-41a7-8935-99d40a6fc626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>f39e15a0-adb2-4bed-acb0-9df820ce3ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>d59d2667-7915-4c5b-b8ec-6b0a89a505c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>eb6eb0a3-5f72-462a-bb66-0e852b1f7034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>8f2e5a19-4009-4f65-beb2-e94b67316884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip149027</value>
      <webElementGuid>67e54ae6-e115-412c-befd-711040c8f602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view_mapel&quot;)/div[@class=&quot;card px-2 py-3 mt-4 fs-poppins&quot;]/div[@class=&quot;row mx-n1 mt-3&quot;]/div[@class=&quot;col-md-12&quot;]/table[@class=&quot;table table-striped table-hover row-border order-column dataTable&quot;]/tbody[1]/tr[2]/td[4]/a[@class=&quot;btn btn-light btn-sm waves-effect waves-light&quot;]</value>
      <webElementGuid>06a1142c-4048-4942-91fd-dbe83e6970e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_mapel']/div/div/div/table/tbody/tr[2]/td[4]/a</value>
      <webElementGuid>ae0f2b65-8db7-47e6-a37b-8b4c4ab640a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quiz'])[2]/following::a[1]</value>
      <webElementGuid>56a58605-960b-4f5c-8bd2-7fcf37437cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ujian'])[1]/following::a[1]</value>
      <webElementGuid>e0fa2685-3d65-4923-9579-5d90b256673c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelompok Penilaian Diklat'])[1]/preceding::a[1]</value>
      <webElementGuid>fa1e0aa7-2eec-4c29-ab0e-2de982a3dfb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelompok Penilaian'])[1]/preceding::a[1]</value>
      <webElementGuid>6a8281e8-b07b-47c6-9c76-00eb835ff8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://101.255.121.243:1180/classroom/scores/lesson/33/50']</value>
      <webElementGuid>963493ca-f4a5-487e-8c5a-bccdb36ce37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/a</value>
      <webElementGuid>53f032d9-7d63-46b7-ad04-79c541bd47d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://101.255.121.243:1180/classroom/scores/lesson/33/50']</value>
      <webElementGuid>fafaa26c-971c-43e5-8d1e-4ce34b91d476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
