<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Status Kelulusan Diklat</name>
   <tag></tag>
   <elementGuidId>090c4ab7-0928-49bb-92ef-3fd6371f2d27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tab_gradtuated_status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tab_gradtuated_status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb91d643-8939-4650-85c4-218773dd7f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab_gradtuated_status</value>
      <webElementGuid>324ba2c8-a213-4ac6-8528-f0e07dfdfe1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active</value>
      <webElementGuid>d57d6a01-0420-4fc1-bea6-2747905483bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>d3d51eb9-3def-402f-9948-0446f32eefb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>00f1cbd8-bf13-445f-b411-1dd2f7def601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#view_gradtuated_status</value>
      <webElementGuid>1f6c0842-06ef-4540-ae98-aa11bd18ff85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>3f3a5889-0a8d-44cf-b672-ca607c907409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc2722fc-beda-4d7c-a930-1e13f9501f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Status Kelulusan Diklat</value>
      <webElementGuid>1c93a5b1-450b-4889-a4d1-a31eec6b243f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_gradtuated_status&quot;)</value>
      <webElementGuid>ed245efa-10b2-4b56-b61b-9d6f52b51c1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tab_gradtuated_status']</value>
      <webElementGuid>96d360ad-45da-4231-958f-346f71c8af45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Status Kelulusan Diklat')]</value>
      <webElementGuid>647f6439-aaec-44fe-9050-d0112efa08da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nilai Sikap Perilaku'])[2]/following::a[1]</value>
      <webElementGuid>2bef86fa-8d93-4663-9b49-9b1a49b33fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mata Pelajaran'])[2]/following::a[2]</value>
      <webElementGuid>ae34bb08-bfa8-4d01-a792-eb99b94f55ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelompok Penilaian Mata Pelajaran'])[1]/preceding::a[1]</value>
      <webElementGuid>9fa38b92-8d04-452d-b101-6f099f4ddd01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Mata Pelajaran'])[1]/preceding::a[1]</value>
      <webElementGuid>f8796fa3-863a-4023-8b48-82088260205d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Status Kelulusan Diklat']/parent::*</value>
      <webElementGuid>38abce6c-50e1-4439-9705-b052521b3021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[13]</value>
      <webElementGuid>4ae9cf1f-7b51-4df6-a74d-8935bd5c0d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[3]/a</value>
      <webElementGuid>07050e54-da5d-4747-a273-a52fbee77cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tab_gradtuated_status' and @href = 'javascript:;' and (text() = 'Status Kelulusan Diklat' or . = 'Status Kelulusan Diklat')]</value>
      <webElementGuid>5cdf0e1b-d109-47a0-a966-b05a96c0f728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
