<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Atur Jadwal</name>
   <tag></tag>
   <elementGuidId>303cf57a-5153-49e3-9446-357f6f08ad0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='set_schedule(this);']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.no-button.no-shadow.btn-sm.delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36865967-fc43-4329-8807-bf87245b5880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn no-button no-shadow btn-sm delete</value>
      <webElementGuid>23592277-10eb-4447-bdb5-3529e9d8c121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>set_schedule(this);</value>
      <webElementGuid>accf07af-e3c8-403b-a22d-7a9fb3b74819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>start_date</name>
      <type>Main</type>
      <value>2022-08-01</value>
      <webElementGuid>d4f9c398-3602-47f0-8c81-3410ef797a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ccl-id</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>33784513-8938-4692-bfd2-be785db12b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cls-id</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>5ee83de3-86c8-455a-aff3-3a72a625d6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mod-data</name>
      <type>Main</type>
      <value>MP-012 - Hukum Pembuktian </value>
      <webElementGuid>9916e72b-bfcf-451f-a7c2-edf3347933c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>142</value>
      <webElementGuid>fe28472b-6703-4942-9bc0-2d74fdcb9291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Atur Jadwal</value>
      <webElementGuid>01d8a455-d36e-4ceb-b1fc-51ca84fe8825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[11]/button[@class=&quot;btn no-button no-shadow btn-sm delete&quot;]</value>
      <webElementGuid>3d0c3d2c-9ba0-4704-a21c-2be25dd69ee7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='set_schedule(this);']</value>
      <webElementGuid>17dfdb83-faf5-46fa-a8ed-cd26508bf87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[11]/button</value>
      <webElementGuid>edfb50a8-e1e9-48db-bbfe-02b1e8354648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::button[1]</value>
      <webElementGuid>4d4d9405-44f6-402f-8b4d-f3db309246a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[1]</value>
      <webElementGuid>0147152d-6781-4111-9043-d064be7e681e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MP-013 - Pra Penuntutan'])[1]/preceding::button[1]</value>
      <webElementGuid>c9cce6c4-3dcc-46ca-ab09-88cb4a1f3d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mata Pelajaran Utama'])[2]/preceding::button[1]</value>
      <webElementGuid>452e19af-20ce-4427-87c7-d3024e041da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Atur Jadwal']/parent::*</value>
      <webElementGuid>2848f12b-8758-4293-b444-2a9e7aaaa9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/button</value>
      <webElementGuid>99ae1594-9c57-45c0-a1a4-c39cbb22fe13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Atur Jadwal' or . = ' Atur Jadwal')]</value>
      <webElementGuid>b52430a6-3ebf-4b23-8811-dc2b20fbf91a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
