<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lokasi_class_location</name>
   <tag></tag>
   <elementGuidId>30bd654e-c032-4a03-be47-48b8758a9a11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='class_location']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#class_location</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b43c9316-fdfd-45d0-aa3c-0ffda26dc1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef6e42ce-a8a9-48c8-ace8-84b38631dca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6d5bc0d6-26bc-4e1d-9655-9281516abc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>class_location</value>
      <webElementGuid>faaabd70-8a08-429d-a063-2e235edfe4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>class_location</value>
      <webElementGuid>428c0dc7-7f2c-45eb-89ab-1ae4c0d35c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi Lokasi</value>
      <webElementGuid>5d16722b-bec3-4533-a44c-50211bbed89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>1a983fa4-feec-46e7-a2be-17f915f697bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class_location&quot;)</value>
      <webElementGuid>9e69151d-4f01-4b3c-8f65-46437b544f5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='class_location']</value>
      <webElementGuid>72ef17f6-58b9-4269-8a33-71fdbbc8a7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[6]/div/input</value>
      <webElementGuid>9948fd1f-4223-4fdf-ba2c-0cbe51ad3898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>7e355dfe-a1ab-457d-bf9b-af3bd95ccd68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'class_location' and @id = 'class_location' and @placeholder = 'Isi Lokasi']</value>
      <webElementGuid>91f35233-27cf-4543-a132-0dab453501e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
