<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AngkatanBatch_class_batch</name>
   <tag></tag>
   <elementGuidId>80579835-6959-4fbc-8ed4-25c7274ae516</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='class_batch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#class_batch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c97a886-6cfa-4851-af81-e6a2b70ff881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbdc15ac-8257-4a1c-9b2f-19e744d25b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>85be8364-1e63-4ba3-86d9-3a22771cf5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>class_batch</value>
      <webElementGuid>c76cc1c7-48a6-4f03-bfb6-5bbb0377f49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>class_batch</value>
      <webElementGuid>0d9af9d9-0bb5-416f-8863-45026fcbdc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi Angkatan/Batch</value>
      <webElementGuid>36b10ffc-7bb1-41d8-a0ea-f6a1fff44b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>184670f7-b2d8-4729-9528-09c9bace815b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class_batch&quot;)</value>
      <webElementGuid>0c2abe39-0e75-432e-bad3-352fdfa62669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='class_batch']</value>
      <webElementGuid>40d7a7a1-a6bb-43d2-b68a-da621167dc6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[4]/div[2]/input</value>
      <webElementGuid>b9d7360e-0940-4a26-8f55-467ccd226803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>a6bb5334-4880-46d2-ae8e-db7acd500b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'class_batch' and @id = 'class_batch' and @placeholder = 'Isi Angkatan/Batch']</value>
      <webElementGuid>e7ef76e9-4552-4c46-8d14-16bcfb9a5c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
