<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_--- Search ---_1</name>
   <tag></tag>
   <elementGuidId>2d102a4e-52fe-40e9-945f-bac188bd194a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-reu_id-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-reu_id-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7c7619f-0026-4c8d-a5b5-57bdd885ba88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>401f24fa-b7f2-4f7f-ad40-25303bf96c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-reu_id-container</value>
      <webElementGuid>af1e7fcc-6495-451d-a8c9-152a8d63eec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>3d362082-af32-4286-8235-29cd0dabff5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d26ccde0-a62e-4c57-89f9-9c14850c7f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--- Search ---</value>
      <webElementGuid>fad1a2cd-58e2-420d-a1d3-06cac90055c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-reu_id-container&quot;)</value>
      <webElementGuid>fb4781ce-9012-4914-874f-db7ea829969e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-reu_id-container']</value>
      <webElementGuid>6b71d924-51d0-49d2-81b8-d3336f1e7e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[4]/div/span/span/span/span</value>
      <webElementGuid>bd6e9191-4565-48b5-b69c-42f672bd20ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[5]/following::span[4]</value>
      <webElementGuid>15357844-bc87-47d0-a77b-eff54266b4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Angkatan/Batch'])[1]/preceding::span[4]</value>
      <webElementGuid>10ccb31b-994f-4857-b201-ffb7c3106949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span/span</value>
      <webElementGuid>f76a654d-4cd8-4ef3-afed-2d636f472d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-reu_id-container' and (text() = '--- Search ---' or . = '--- Search ---')]</value>
      <webElementGuid>29a34e24-1ef2-4ca4-b97d-5cb46f552b1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
