<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tambah</name>
   <tag></tag>
   <elementGuidId>03f8b589-30ae-4649-b80f-da13af881dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick=&quot;add_organizer('tbl_organizer')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.btn.btn-danger.waves-effect.waves-light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>69828938-985b-405e-8cf1-b5e2ce2a20ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger waves-effect waves-light</value>
      <webElementGuid>04cc688f-00d8-4d0a-a166-ca3cf6311b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>add_organizer('tbl_organizer')</value>
      <webElementGuid>5d8735eb-e535-4a74-81b1-f9c15a8f4d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah</value>
      <webElementGuid>f6f4a06b-94f0-4fde-8b18-a2d151efab29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2&quot;]/div[@class=&quot;d-flex justify-content-end&quot;]/span[@class=&quot;btn btn-danger waves-effect waves-light&quot;]</value>
      <webElementGuid>8b080cef-ec36-47fe-9be9-40c0c5ff6a3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick=&quot;add_organizer('tbl_organizer')&quot;]</value>
      <webElementGuid>f275532c-f0ca-4c70-8389-540acc89cbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[10]/div[2]/div/span</value>
      <webElementGuid>e8cf57dd-5879-406f-b7e5-ab766b712f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::span[3]</value>
      <webElementGuid>0c988151-ef95-4cf6-93e2-60f1d327a4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penyelenggara'])[4]/preceding::span[1]</value>
      <webElementGuid>7966fc7a-b7c4-4d0c-b975-0c6043f53dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fungsi'])[1]/preceding::span[1]</value>
      <webElementGuid>58188dd2-4bdf-40b9-bee3-216391d399a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah']/parent::*</value>
      <webElementGuid>dbc435c1-c6f9-4c03-80e1-92ec75168379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/span</value>
      <webElementGuid>805e9d93-cf73-474b-9ce5-0d6a76856074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tambah' or . = 'Tambah')]</value>
      <webElementGuid>21da5317-3bd2-4b44-8b48-a3d46f54ca99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
